### ISSUE TITLE
Roslyn-Based GenAPI Backend

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade#10291]
This epic is a prerequisite for #9672.

# Goals and Motivation

One of the steps to close the gap between the existing official build and the [.NET source-build](https://github.com/dotnet/source-build) is enabling prebuilt detection on the individual product repository level. 

Currently, we detect new prebuilt introduction when source-building the whole product. This not only requires a lot of effort from the A&D team, but also takes significant time to remediate as the prebuilt detection is done late in the process. This late detection can seriously impact the product release as has been proven several times in the past.

Our goal is to introduce prebuilt detection on an individual product repo level so that developers could detect prebuilts during their PR validation and resolve the problem by generating the SBRPs themselves with minimum assistance from the A&D team. Unfortunately, the current SBRP generation tooling,  [GenAPI](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.GenAPI), is not sufficient for this scenario as it uses the old Microsoft Common Compiler Infrastructure (Microsoft CCI) to generate the API surface for individual packages. The Microsoft CCI backend needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.

**The goal** of this epic is to introduce a new backend for the GenAPI tool that would be based on Roslyn, rather than on Microsoft CCI.

![Drawing1](https://user-images.githubusercontent.com/15262391/212115979-6b626e75-bfa5-4f1a-aa6a-0223d08c03e8.png)

# Business objectives:
- [x] Provide the Roslyn-based tooling for the reference assemblies generation
  - We need the product developers to be able to generate the source-build reference packages (SBRPs) themselves so that the burden isn't solely on the A&D team.
  - The current CCI-based tool needs to be periodically updated to reflect the latest language changes which is often a time-consuming task requiring significant expertise.
- [x] Design the solution so that the Runtime team can build upon it and leverage the shared code base.
  - The Runtime team want to use the Roslyn-based tooling to generate reference source files from implementation assemblies and utilize the common codebase in their AsmDiff and the ApiCompat tools.
- [x] Clarify the ownership of the new, shared codebase with the Runtime and SDK teams
  - Since the new tooling aims to provide codebase that will be used by other teams, we need to have clear understanding of who is responsible for maintenance and bugfixes of the shared codebase in the future.
- [x] Code generation issues are solved directly in Roslyn, rather than via workarounds in the tooling
  - One of the primary expectations of moving to Roslyn-based tooling is that we will keep be able to keep up with a new language features "for free" by using Roslyn itself, rather than having to implement support for them as it has been the case with the CCI backend.
  - Any potential issues found during the development of the new tooling should be fixed ideally directly in Roslyn.

# Milestones
- [x] Investigate Cci-based GenAPI implementation, investigate related/similar projects in dotnet/\*, azure/\*, build relationship with Runtime and Roslyn teams **2w**
- [x] #11863
- [x] Introduce a shared library that incapsulates logic of loading, traversing of assembly symbols [**Due**: 14th of Oct]
  - [x] Introduce solution structure (Shared lib, Tools, MSBuild tasks, Tests), implement loading assembly symbols **1w**
  - [x] Implement traversing of assembly symbol (namespaces, named types, attributes, members), introduce interfaces for building/reconstructing source tree **1w**
  - [x] Implement sorting and filtering of assembly symbols (features like `allow public only`, `filter out the list of attributes`) **1w**
  - [x] Implement UTs and cover assembly symbols loading, traversing, C# code generation, filtering. **2w**
    - [x] #11144
- [x] #11136
- [x] #11616
- [x] #11617
- [x] #11691
- [x] #11225
- [x] #12009
- [x] #11726

# Roslyn API related issues
The list of bugs and unsupported features of the Roslyn API (IDE specific) found during developing and testing. They are summarized in the [Summary of issues found during testing of the Roslyn-based GenAPI](https://github.com/dotnet/arcade/issues/12009) issue.
### Language feature support
- [x] #11848
- [x] #11938
- [x] #11895

### Bugs with higher priority
- [x] #11734
- [x] #11850
- [x] #11853
- [x] #11881
- [x] #11884
- [x] #11935

### Bugs with lower priority
- [x] #11989
- [x] #11937
- [x] #10526
- [x] #11934
- [ ] https://github.com/dotnet/roslyn/issues/66966
- [ ] https://github.com/dotnet/roslyn/issues/67019

# Roslyn-based GenAPI issues found during testing
- [x] #11347
- [x] #11254
- [x] #12462
- [x] #11097
- [x] #11222
- [x] https://github.com/dotnet/arcade/issues/11615
- [x] #11614
- [x] #11814
- [x] #11234
- [x] #11232 
- [x] #10270
- [x] #10271
- [x] #12555
- [x] #12578
- [x] #12609
- [x] #12657
