### ISSUE TITLE
Operational efficiency and consolidation - Fall 2022

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10450]
### Overview
To meet our goals of keeping our engineering systems up-to-date and as efficient as possible, we will deliver feature work that reduces the complexity and Azure-spending usage of our systems, while at the same time moving these systems onto long-term supported versions of .NET Core.  As part of this work we will build the ability to detect extraneous objects in our subscriptions, allowing us to respond and clean them up.  This epic will seek to reduce known, tech-debt-derived complexity and Azure spending for daily operations by the .NET Core Engineering Services team, as well as offload regularly executed processes to the DncEng vendor team, freeing up engineering FTE time.

Consolidating the service fabric clusters we use will permanently save 104 D_v3 cores in Azure, along with the long-term costs of patching, maintaining, and deployment to this cluster. This also means fewer Service 360 issues to respond to when the clusters become out of compliance, and simpler porting (half the work) if we need to move to a different data center or VM size. Moving the autoscaler into the services deployed by the dotnet-helix-service repo will allow deployment of updated build and test images even when the scaler is experiencing issues, making updating build images easier.

#### Goals
- [x] Reduce core usage, improve speed of deployment, eliminate patching costs of services provided by DncEng by consolidating two other systems into the same service fabric cluster (104 cores, 20-30 minutes per CI build)
- [ ] Ensure that all .NET Core Engineering services are running on long-term supported versions of .NET Core Framework
- [x] Onboard more machine-maintenance tasks to vendor team

#### [Move dnceng projects from netcore3.1 to net6.0](https://github.com/dotnet/arcade/issues/8998)

|Deliverable|Owner(s)|Completion Date| Status | Notes|
|-|-|-|-|-|
| dotnet-helix-service | @ChadNedzlek | 5/11/2022 | [Complete](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22747) | |
| arcade-services | @ChadNedzlek | 5/04/2022 | [Complete](https://github.com/dotnet/arcade-services/pull/1876) | |
| dotnet-helix-machines  | @garath | 1/18/2022 | [Complete](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26102) | |
| dotnet-migrate-package | @garath | 8/30/2022 | [Complete](https://dev.azure.com/dnceng/internal/_git/dotnet-migrate-package/pullrequest/23817) | |
| dotnet-xliff-tasks | @jonfortescue | 8/17/2022 | [Complete](https://github.com/dotnet/xliff-tasks/pull/645) | |
| dotnet-source-indexer | @jonfortescue | 8/30/2022 | [Complete](https://github.com/dotnet/source-indexer/pull/104)  | |

#### [Move Helix Autoscaler / VM Cleaner into main Service Fabric cluster](https://github.com/dotnet/arcade/issues/10018)

|Deliverable|Owner(s)|Completion Date| Status | Notes|
|-|-|-|-|-|
| Port autoscaler service fabric to dotnet-helix-services cluster | @MattGal | 9/10/2022 | Completed | |
| Port VM cleaner to dotnet-helix-services cluster as web job | @MattGal | 9/21/2022 | Completed | |
| Decommission old resources once moved | @MattGal | 10/1/2022 | Completed | |

#### [Operationalize weekly image update tasks](https://github.com/dotnet/arcade/issues/10353)

|Deliverable|Owner(s)|Completion Date| Status | Notes|
|-|-|-|-|-|
| Visual Studio version update tick-tock onboarded to vendor team | @jonfortescue | 09/30/2022 | Complete | |
| Azure Gallery base image update version work onboarded to vendor team | @MattGal | 10/15/2022 | Complete | |
| Vendor team can generate rollout release notes | @jonfortescue  | 11/04/2022 | Complete | |
| Vendor team can generate rollout pull requests | @jonfortescue | 11/04/2022 | Complete | |

### Completed ###
|Deliverable|Owner(s)|Completion Date| Status | Notes|
|-|-|-|-|-|
| [Move Helix Autoscaler / VM Cleaner into main Service Fabric cluster](https://github.com/dotnet/arcade/issues/10018) | @MattGal | @10/1/2022 | Complete | 

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

**Comment by MattGal** [comment]
woohoo!
