### ISSUE TITLE
Move aspnet/Extensions to .NET Core 3 Engineering Ecosystem

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#1049]
- [x] Public CI is using VSTS (https://dev.azure.com/dnceng/public)
- [x] Official builds in VSTS (https://dev.azure.com/dnceng/internal)
- [ ] Build using shared toolset (Arcade SDK)
- [x] Dependency flow is enabled
