### ISSUE TITLE
.NET 8: Vertical Build Tooling

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#10588]
This epic covers vertical build tooling for .NET 8. The tooling has two pri-0 goals:

- [ ] Enable teams to identify and triage orchestration points within the .NET 8 build.
- [ ] Enable continued auditing of orchestration points.

This tooling will require understanding the build YAML as well as the source-build (or product build) dependency graphs and applying rules and analysis on top of them.

This tooling shares a lot of similarities with tooling that would be required to understand where time is being spent within a build. The tooling should be designed in such a way that it could be extended to audit and report on build efficiency.

General requirements:
- [x] Tooling should be able to understand .NET's Azure DevOps builds and build dependency graphs of the stages and jobs in the build.
- [x] Tooling should be able to understand the environments that each job is run in (vm, container, etc.)
- [x] Tooling should allow for general analysis of the build dependency graph.
- [x] Tooling should be able to produce reports and pictures of the graph and/or analyses
- [x] Analysis should include:
  - [x] orchestration points where job environments change from one to another (e.g. windows->linux_
  - [x] Build overhead analysis. How much time is spent waiting on machines, cloning code, etc.
- [x] Analysis input data should be configurable by the user. For instance, defining whether a specific job is interesting from an orchestration standpoint or not.
- [ ] Should be testable

**Comment by tkapin** [comment]
@mmitche Are any of the points above already completed by the tooling you built to detect and visualize the joints? Seems like at least the first part of this epic is done, correct?

**Comment by mmitche** [comment]
Most of the points. Minimal testing at this point but it works well enough. Given that Viktor and others seem more confident about the vertical build changes (that they will not be too difficult), and that most repos do not have a ton of problems, I think we can probably close the epic and come back to it if we need to gather more information.

**Comment by tkapin** [comment]
Good, makes sense. From the planning perspective, should we plan to assign some resources to finish this in the NET8 timeframe or it's more likely that the second part (joint monitoring) wouldn't be needed at all in light of Viktor's findings?

**Comment by mmitche** [comment]
> Good, makes sense. From the planning perspective, should we plan to assign some resources to finish this in the NET8 timeframe or it's more likely that the second part (joint monitoring) wouldn't be needed at all in light of Viktor's findings?

It may not be needed. I think we can continue to use/develop it as-needed but it's good for now.
