### ISSUE TITLE
Engineering documentation for epic hand-off (done done done)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10607]
As we're close to finishing up the Dev WF/Known Issues epics, we will need to provide some solid documentation on how all our services work that were build up for the projects encompassed in these epics, so that a few of us aren't the only ones to understand how they work. 

- [x] high level diagrams of the parts that work together and resources used (Test reporting missing)
- [x] links to where engineering folks can find customer facing documentation
- [x] links to dashboards, monitoring, et cetera
- [x] write down any specifics that engineering folks would need to know when troubleshooting

**Comment by AlitzelMendez** [comment]
I am addressing the `write down any specifics that engineering folks would need to know when troubleshooting` in the PR:  https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/28478

**Comment by AlitzelMendez** [comment]
Added high level diagram for Build Analysis in: https://dev.azure.com/dnceng/internal/_git/dotnet-eng-wiki/pullrequest/29198?_a=files

do we want to keep this open for the diagram of test reporting? @missymessa

**Comment by missymessa** [comment]
Yeah, keep it open and assign it to me so I don't forget!

**Comment by missymessa** [comment]
PR merged. Closing.
