### ISSUE TITLE
Get Source.Dot.Net to a sustainable state long term

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/arcade#11032]
Today we have Source.Dot.Net that lets a user walk through the code for CoreFX for Windows.  @stephentoub and @danmosemsft would love to be able to walk through the Linux version of the code as well.  

Goals:
- [ ]  Create a Linux version of Source.Dot.Net
- [ ]  Get the repo into a state where contributors can easily help out
- [ ]  Create alerting to know when the site is not functioning or is down

[Original issue](https://github.com/dotnet/core-eng/issues/8790)

# Recently Triaged Issues
All issues in this section should be triaged by the v-team into one of their business objectives or features.
- [ ] https://github.com/dotnet/arcade/issues/7024

**Comment by stephentoub** [comment]
Note the current source.dot.net has Linux; we'd also like to be able to browse Windows, and once we have the facilities for multiple targets, adding more like macOS would be welcome.

**Comment by garath** [comment]
This service has moved to a new owner. Improvements are being driven from there.
