### ISSUE TITLE
SDL Pass for DncEng-owned areas, Fall 2022

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#11058]
## Goals

- [ ] SDL Fall 2022 Assement completed for all the following areas

## Milestones
| Assessment | Owner | Estimated Date of Completion | Status | 
| --- | --- | --- | --- |
| Helix | @MattGal | 2022-12-01 | Completed |
| Arcade | @MattGal | 2022-12-01 |  Completed |
| Arcade Services - Maestro | @garath | 2022-12-05 | Completed |
| Arcade Services - Grafana | @garath | 2022-12-05 | Completed  |
| Arcade Services - DotNet Status Web | @jonfortescue | 2022-11-07 | Completed |
| Arcade Services - Rollout Scorer | @jonfortescue | 2022-11-07 | Completed |

## Assement pages:

**Instructions:**

- 1. Complete all work items from the below linked queries.
- 2. Use previously resolved issue(s) to inform how to proceed with the work.
- 3. Once done, check the below box and update status table above

- [x] [Helix](https://devdiv.visualstudio.com/DevDiv/_compliance/product/bba16e40-9b89-4f01-3f53-c6f614242f7a/assessments)
- [x] [Arcade](https://devdiv.visualstudio.com/DevDiv/_compliance/product/6e28fa48-4e88-900c-d557-c9c74887a052/assessments)
- [x] [Arcade Services - Maestro](https://devdiv.visualstudio.com/DevDiv/_compliance/product/e20b6406-32c6-6bc3-df7b-5eaf06189c8a/assessments)
- [x] [Arcade Services - Grafana](https://devdiv.visualstudio.com/DevDiv/_compliance/product/07261898-fe7d-c80b-00a4-184ea4b49f41/assessments)
- [x] [Arcade Services - DotNet Status Web](https://devdiv.visualstudio.com/DevDiv/_compliance/product/1c5e98f3-57ce-1139-61a0-7c1319eb3c4c/assessments)
- [x] [Arcade Services - Rollout Scorer](https://devdiv.visualstudio.com/DevDiv/_compliance/product/aa2dff06-23ba-faa5-edab-0b3832d6a5eb/assessments)

**Comment by garath** [comment]
This is done! S360 should update in a few hours.
