### ISSUE TITLE
AzDO Issue #3517

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#11116]
[Azure Boards WorkItem](https://dev.azure.com/dnceng/internal/_workitems/edit/3517)

**Make checkboxes**

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [x] https://github.com/dotnet/arcade/issues/11117
- [x] https://github.com/dotnet/arcade/issues/11118
- [x] https://github.com/dotnet/arcade/issues/11119
