### ISSUE TITLE
VMR GA checklist

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#11400]
### Implementation 
- [x] `source-mappings.json` references documentation (there's TODOs)
- [x] VMR `README.md`
    - [x] links into the new documentation
    - [x] contains manifest
    - [x] mentions WIP
    - [x] contains development instructions
    - [x] Link the Roadmap
- [x] `THIRD-PARTY-NOTICES.TXT` is generated

### Content validation
- [x] Verify that links from README / source-mappings.json work
- [x] Tarball contents are compared
- [x] We tried building it

### To validate on GA
- [x] Create cannonical announcement Arcade issue
- [x] Create SB discussion
- [x] Make the VMR public
- [x] Post the announcement
