### ISSUE TITLE
Separate DncEng and Product Construction pieces from dotnet/arcade-services

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12178]
### Overview

The dotnet/arcade-services repo contains functionality used in several places, including the Helix and Maestro services as well as assorted utilities used for dependency flow, Grafana monitoring, secret management automation, and telemetry gathering.  These pieces are used for day-to-day work of both the .NET Core product teams and the engineering services team.

With the move to diverge the new "Product Construction" team (tentative name referred to as "ProdCon" later on this issue for brevity) away from the .NET Core Engineering Services team, the ownership of this repo will need to be transferred to the new team and any components that remain under the purview of the DncEng team will need to be moved into different repositories.  To ensure billing correctness, any Azure components created from this repo need to moved if owned by the ProdCon team.  Any such migrations are likely to cause some amount of downtime, which needs to be accurately planned and communicated in advance.

#### Goals

- [ ] Inventory and determine final ownership of all components in dotnet/arcade-services
- [ ] Move all ProdCon-owned components and related content into their Azure subscription(s) for billing purposes.
- [ ] Move all DncEng-owned components' sources into other repositories.  Ideally we should use existing repos where possible (such as dotnet/arcade), but at least the goal is it create as few new repositories as possible.
- [ ] Communicate downtime (if any) caused by Azure migration to the .NET Core Engineering Services Partners team in advance to prevent surprises.

### Required for Epic

|Deliverable|Owner(s)|Completion Date| Status | Notes|
|-|-|-|-|-|
| [Inventory of components in dotnet/arcade-services](https://github.com/dotnet/arcade/issues/12180) | - | 2022 Jan 27 | Complete | - |
| [Determine ownership of dotnet/arcade-services components](https://github.com/dotnet/arcade/issues/12182) | TBD | 2022 Jan 27 | Complete | |
| Move all ProdCon-owned components into their Azure subscription(s) for billing purposes | TBD | 2023 Feb 03 | Not Started | To be replaced with individual issue(s) for subdividing work when inventory work completes |
| Move all Prodcon-owned arcade-services components' sources into other repositories. | TBD | 2023 Feb 17 | Not Started | To be replaced with individual issue(s) for subdividing work when inventory work completes |

### Completed ###
|Deliverable|Owner(s)|Completion Date| Status | Notes|
|-|-|-|-|-|
|  |  | |  |

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.
#12681

**Comment by tkapin** [comment]
@garath - the first two items in the table are marked as complete, but the corresponding issues are open with no comments. Do you know is something has been documented or done within this epic?

**Comment by garath** [comment]
Closing this since the focus was reevaluated after the reorg. dotnet/arcade-services#2325 is its successor.
