### ISSUE TITLE
Inventory of components in dotnet/arcade-services

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12180]
### Task items:
- [ ] Produce a list of all components (packages, CLIs, console applications, etc.) in the dotnet/arcade-services repo
- [ ] For each component, include an entry using the template listed below
- [ ] When completed, add this information in the issue and close.

#### Sample component description
Component name:
Repo path(s): (Source code location)
Purpose: (Short description of purpose)
Type: (What kind of component this is; NuPkg, .NET Core CLI, console app, grafana monitoring, etc)
Related Azure resource locations: (Subscription / Resource Group / object names, or N/A if not applicable)

Include relevant notes if applicable (e.g. "seems like dead code", etc)

**Comment by tkapin** [comment]
The table in the parent epic says this is complete. Are there any captured results?

**Comment by missymessa** [comment]
I think I'm having deja vu. I think this work was already completed as a part of the Ownership Alignment epic. Going to close this one. 

/cc @dkurepa @tkapin in case you think this work still needs to be done :)

**Comment by tkapin** [comment]
Nope, closing this is fine. We have a good understanding of what are the components in this repo now after the code has been aligned with the other repos.
