### ISSUE TITLE
Where did my budget go?

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#12241]
- [ ] Provide clear differentiation between Product teams spend and Engineering Services infrastructure spend
- [ ] Expose granular data of Azure resources spend (VMs usage, storage, bandwidth, etc.) for Product teams and Engineering Services
- [ ] Cost analysis per repository/definition
- [ ] Provide metrics for Product teams usage including:
  - [ ] Number of Pull Requests
  - [ ] Resources spent per Pull Request
  - [ ] Resources spent in CI builds

| Work | Issue | Due Date | 
| -- | -- | -- |
| **Divide S360 report between product and infra spend** | https://github.com/dotnet/arcade/issues/12493 | mid-March | 
| Figure out data for S360 budget report (working with DDFUN to get this data) | https://github.com/dotnet/arcade/issues/12514 | | 
| Migrate infra services to separate subscriptions (working with PME v-team to do this work) | | |
| Update S360 reporting to show divisions | | | 
| **Azure Resource Spend** | https://github.com/dotnet/arcade/issues/12494 | end of March | 
| **Tracking Helix Overhead Spend** | https://github.com/dotnet/arcade/issues/12498 | mid-April |
| Identify areas where "waste" is occurring | | |
| Update telemetry to track "waste" better | | |

Possible efforts
- [ ] Clean Helix jobs data (enforce build data)
- [ ] Track miscategorization of R&D work
- [ ] Create new service tree entries
- [ ] PowerBI report for product LT

**Comment by missymessa** [comment]
Closing epic.
