### ISSUE TITLE
Improve Helix performance, reliability, and ease-of-use for preview 3

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#1227]
- [x] Payload upload time is minimized by parallelizing and removing redundancy in the JobSender
**ETC: 8 Feb 2018**
- [x] The JobSender is made more reliable by hardening it against network glitches and payload collisions
**ETC: 22 Feb 2018** (edit: date slipped back a week due to snow and illness)
- [x] Customers can easily use documentation to get started with Helix
**ETC: 8 Mar 2018** (edit: date slipped back a week due to snow and illness)
