### ISSUE TITLE
Stabilized product build using "channels"

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1239]
As we approach RTW, we will need to produce a number of product builds (flow dependencies) that have stabilized bits where needed (e.g. coreclr doesn't need to produce stabilized bits, but corefx does for most packages.

In prodcon v1, we did this by basically producing a build to an isolated drop but not publishing those results to customer-used locations.  Basically, you don't publish these stabilized non-final bits to the main myget or nuget feeds, as they may need to be overwritten.

For prodcon v2, we will need to do something similar, but with a twist.  Because the repository dependencies are explicit in the source, the source must have checked in references to stabilized dependencies.  Of course, until we actually get a final build, we couldn't check those into the release/3.0 branches.

The rough plan had been to use a channel branch to do this.  We would branch the "3.0 Release" channel into a "3.0 Release - Stabilized" channel with a parallel set of branches (the normal release branches would be parent of these branches), and stabilized dependencies would flow through this channel.  Outputs on this channel would not be made visible on shared locations (e.g. myget) until the final build is done.

There are still a number of details to work out here, as well as potentially some infra work.  Known questions:
- How do we instruct repos to produce stable bits
- How do we ensure that bits are not pushed to shared locations
- How are inter-branch merges (if necessary) done without much intervention (as they would likely have conflicts)

When this epic is done:
- [ ] Complete build can be composed with stable bits where necessary
- [ ] Stable binaries can be flowed more than once without polluting shared lcoations
- [ ] Stable build drops can be produced and tested.
- [ ] Process by which final release bits are produced and from which branch is well understood (e.g. if a parallel set of branches is used, do those commits go back into the parent release branches?)

**Comment by markwilkie** [comment]
This is probably the better version of https://github.com/dotnet/arcade/issues/435?

**Comment by mmitche** [comment]
Damn, I thought I might already have this somewhere.  I'll close the other one.

**Comment by markwilkie** [comment]
My impression is that this is now done as part of the internal build stuff.  Can you guys confirm (or not)?  @mmitche @jcagme @riarenas @JohnTortugo

**Comment by mmitche** [comment]
Mechanism is the same and @riarenas said it works at the moment. We should add scenario testing in arcade-services for flowing stabilized or internal bits between repos. We should add testing in arcade-validation testing production of stabilized bits.

**Comment by mmitche** [comment]
This has been completed as part of #1824
