### ISSUE TITLE
Longer term S360 work

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#13135]
# Goals and Motivation

While some S360 fixes can easily be done as part of our Shared Service Advisors rotation or regular update and rollout cadence, we need to track larger work and determine our costs in this area. Note this epic does not cover _all_ S360 issues since many will be handled directly by our vendors or DDFun or do not require a significant time investment i.e., the SSA can handle them. This epic also excludes S360 exception requests and other mostly-external issues (anything where we're primarily waiting and seeing).

# Business objectives

This covers both principles and goals.

- [ ] Our services and infrastructure meet all applicable company security requirements
  - [ ] Do **not** lose track of S360 work items
  - [ ] Measure our investment in S360-specific work
- [ ] Process for S360 issues is sustainable for the .NET Engineering Services team
- [ ] Actions Core-Eng take relating to S360 are documented, minimal, and repeatable enough for the team (perhaps the .NET Shared Service Advisor for quicker fixes) to handle without a significant drop in service in other areas

# Potential patterns

- [ ] Core-Eng gets involved when vendors cannot take action on their own and an action would otherwise legitimately miss its SLA
  - [ ] We will assess and resolve S360 issues in a timely manner
  - [ ] We will communicate reasonable end dates to management and S360 KPI owning teams
- [ ] Core-Eng is caught up on our S360 backlog, especially out-of-SLA items

# Additional information

- https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki?pagePath=/Documentation/Operations/Service%20360

**Comment by dougbu** [comment]
A few issues that may fit here (need to check on status and get a better idea of the effort required)
- [ ] #12858
- [ ] #10083
- [ ] #10345
- [ ] #10824
- [ ] #10945
- [ ] #10946
- [ ] #10957
- [ ] #12022
- [ ] #12145
- [ ] #12281
- [ ] #12607
- [ ] #12975
- [ ] #13088

**Comment by dougbu** [comment]
Added all issues mentioned just above to this epic. Some were previously associated w/ epics, but all such epics are closed.

Most of these issues have the `FROps` label while one or two have the `Operations` label. I left that alone because we haven't determined the costs. That is, S360 tasks that can be done by SSA shouldn't be in this epic.

**Comment by dougbu** [comment]
Linking in another issue so that I can clean up my assignments list:
- [ ] #13007

**Comment by dougbu** [comment]
unassigning myself. /cc @ilyas1974 @garath

**Comment by missymessa** [comment]
Looks like all linked issues were closed. Closing!
