### ISSUE TITLE
Dev WF: Build Analysis support for the runtime team's merge on red efforts

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13309]
# Motivation and Business Impact

The Runtime team is aligning their Pull Request policies so that PRs that fail the validation process are allowed to be merged as long as all the issues in the PR are understood as known issues.

This effort is relying on the Build Analysis and Known Issues features provided by Engineering services to make the final say on whether a PR is allowed to be merged or not. The goal of this epic is to identify and implement the features and additional tooling needed from the Engineering services team to support the runtime team's efforts.

Additionally, as these features take a more active role in the PR validation process, we need to ensure the stability and performance of the Build Analysis and Known Issues features as its usage ramps up.

# Areas of Focus

We have identified three main areas of focus for this epic:

* **The Build Analysis check should report as successful when all the issues encountered during the analysis have a matching Known Issue**: Currently, the check reports a failure status for any errors found during analysis. We should identify any additional tooling needed to support this.

* **UX improvements to the Build Analysis and Known Issues features**: We have received some feedback about potential improvements around the user experience for filing Known Issues and tracking their impact. We will likely receive even more feedback as this effort progresses. As part of this, we will continue monitoring and working through sentiment feedback issues for point-in-time problems with the features and documentation of these features.

* **Stability Improvements:** As the Known Issues and Build Analysis features become part of the critical path for merging a PR to the Runtime repository, we need to ensure that the service is able to keep up with the increased load.

# Business Objectives (When is the epic done?)
* [x] The Build Analysis and Known Issue features allow for a PR to be merged when all the errors found during validation builds match an existing Known Issue.
* [x] Tooling (reports, dashboards, helper scripts/tools) is sufficient for the creation and tracking of Known Issues.
* [x] Customer feedback from the sentiment tracker is tracked via a GitHub issues and the customer agrees with the next steps.
* [x] The infrastructure backing the Known Issues and Build Analysis features is reliable, and scales to the demands of the runtime repo's usage.
* [x] Ensure monitoring and alerting coverage for the Build Analysis and Known Issues features is sufficient to determine their health.

# Metrics for Success
TBD

# Milestones
We have split the project into 5 phases. Individual issues related to each phase can be tracked via this GitHub Projects view: https://github.com/orgs/dotnet/projects/86/views/49

The estimated completion dates for each phase are:

* 6/2: Phase 1: Reliability
* 6/9 Phase 2: Adoption and usability
* 6/23 Phase 3: Marking build analysis green 
* 7/25: Finishing up the effort with phases 4 and 5, and whatever additional feedback we receive after we have made the check green

**Comment by jkotas** [comment]
> UX improvements

Nit: Any chance you can delete ".NET Result Analysis" text from the UI (it is in large font at the top of the build analysis page), or at least rename it to something more fitting? ".NET Result Analysis" does not describe well what is on the page.

**Comment by riarenas** [comment]
Thanks for the feedback @jkotas, 

We will process feedback like this in two ways:
	
**Feedback related to something you see specifically in the build analysis check, or with one of the docs:** Use the thumbs up/down button at the bottom of the check/doc. This will create an issue in Arcade, and capture the state of the check when it was clicked. If the dev filing the feedback chooses to disclose their alias, we will follow up with them directly to get some agreement on next steps. .
	
**General feedback or requests for the build analysis/known issue features:**  File a regular issue in Arcade. Anything related to this work will get triaged into the epic for discussion and tracking.

**Comment by jkotas** [comment]
> Feedback related to something you see specifically in the build analysis check, or with one of the docs: Use the thumbs up/down button at the bottom of the check/doc. This will create an issue in Arcade, and capture the state of the check when it was clicked

I have done this earlier and https://github.com/dotnet/arcade/issues/10592 was opened on that and it was won't fixed. It is a nit that should be trivial to fix that would make the UI look more polished. It is the first thing that one sees on the Build Analysis page. Giving things the right names and titles matter. The non-sensical title of the page hurts credibility of the system.

**Comment by riarenas** [comment]
You should feel empowered to reopen any issues where you disagree with the resolution. Trying to track the discussion of individual issues in the epic would get out of hand easily, so we want to keep these discussions on the issues themselves.

**Comment by missymessa** [comment]
> Nit: Any chance you can delete ".NET Result Analysis" text from the UI (it is in large font at the top of the build analysis page), or at least rename it to something more fitting? ".NET Result Analysis" does not describe well what is on the page.

Can you take a screenshot of which text you're referring to? Some of the text on the GitHub check is required by GitHub.

**Comment by riarenas** [comment]
#10592 has the context, let's stick to discussion there.

**Comment by missymessa** [comment]
Handled by https://github.com/dotnet/dnceng/issues/556 epic.
