### ISSUE TITLE
Implement new issue management and epic tracking process for team

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13374]
Once we decide on which process we want to do, let's implement it: 
- [ ] Update async triage tool
- [ ] Update any existing webhooks for the current process
- [ ] Migrate existing epics/issues to new repo

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
This issue was broken up into several other issues. Closing.
