### ISSUE TITLE
Sentiment Tracker issues to mirror to dotnet/dnceng

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13589]
- [x] Ensure that new Sentiment Tracker issues are mirrored to dotnet/dnceng instead of dotnet/arcade.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Release notes not necessary

**Comment by missymessa** [comment]
It worked! Closing. 

https://github.com/dotnet/dnceng/issues/195
