### ISSUE TITLE
Milestone Management

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#13595]
- [ ] When an epic issue is closed, the associated milestone is also closed. Do not allow an epic to be closed if there are still open issues associated with that epic's milestone. 
- [ ] When an epic label is added to an issue, include the title of that issue in the list of milestones
- [ ] When an epic issue's title is updated, update the name in the milestones
- [ ] Do not allow an epic label to be removed from an epic if any open issues are still associated with it

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
PR: https://github.com/dotnet/dnceng/pull/425
