### ISSUE TITLE
Configuration system refactoring

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#1434]
Let this issue serve as a meta-issue to track potential refactoring to be done to configuration system infrastructure. I'll open issues to address these when we're ready to do them.

- [x] Eliminate cases where CoreFx properties are being used in the generic configuration system.
- [x] Eliminate configuration.props and instead always have an outer build when Configuration isn't explicitly set.
- [x] Eliminate overloading of Configuration, instead use TargetFrameworks and move ConfigurationGroup->Configuration, ArchGroup->Platform.
- [ ] Consider normalizing configuration strings to always have the same format (either with or without defaults included).
    - This may be as simple as allowing https://github.com/dotnet/buildtools/blob/64e2e93c0560ceb2108c69fdb0d8795d2f7b52ba/src/Microsoft.DotNet.Build.Tasks/GenerateConfigurationProps.cs#L248 to apply via TreatAsLocal for Configuration
- [ ] Consider making input configuration strings case-insensitive and normalizing to the case in the model.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/corefx/issues/32375 related to this.

**Comment by ViktorHofer** [comment]
@ericstj I believe most of the work being tracked here is completed. Closing.
