### ISSUE TITLE
Product Construction 2.0 Design

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#156]
ProdCon represents the infrastructure required to build .NET Core using a multi-repo approach.

It is considered to be complete when:
- [ ] Build .NET Core multiple times a day from source as well as the Microsoft Product release.
- [x] Repository dependencies flow quickly and reliably.
- [ ] We can trace the set of dependencies (repo/sha/version) from source-build repos within the .NET Core ecosystem.
- [ ] We can visualize and report the state of the product
