### ISSUE TITLE
Fork Xunit Console Runner to Arcade

### ISSUE THREAD

**Issue by josalem** [dotnet/arcade#1613]
This issue is for tracking work on forking the xunit console runner.  

### Reason
The current xunit console runner (v2.4.x) is no longer maintained, so we will be forking the code for longer term maintenance and feature updates until a viable alternative presents itself.

### TODO
- [x] Initial Code push
- [x] Infrastructure for consuming NuGet (covered by Arcade as far as I know)
- [ ] Planning on ownership, feature addition, etc.
- [x] Incorporate changes from dotnet/buildtools#2035
- [ ] Address dotnet/coreclr#19890
...

CC - @ViktorHofer

**Comment by josalem** [comment]
@BruceForstall

**Comment by BruceForstall** [comment]
cc @echesakovMSFT

**Comment by BruceForstall** [comment]
cc @RussKeldorph

**Comment by BruceForstall** [comment]
@ViktorHofer @josalem Now that https://github.com/dotnet/arcade/pull/1627 is merged, what is the plan for addressing the bugs/issues referenced above?

**Comment by josalem** [comment]
There isn't a plan in place yet.  We could create a label for xunit runner issues and create issues/PRs with that label.  That will give us a nice view of what work needs to be done since I'm sure I'm missing a few in the checklist above.  I was planning on tackling the response files work (dotnet/buildtools#2035) that @A-And added to the old custom runner in the near future.

**Comment by ViktorHofer** [comment]
We aren't using this runner in corefx for netcoreapp and netfx right now as there is no necessity to do so but if it's blocking when can switch over to it. Right now we use a repackaged version of it for uap (UWP console app) and uapaot (netcoreapp2.0 + WINDOWS_UWP constant).

**Comment by echesakovMSFT** [comment]
@josalem @ViktorHofer Can you please tell how far we are from getting this fork published to NuGet?

I have a fix https://github.com/xunit/xunit/pull/1846 that I would like port to the fork and consume the fork version of xunit.console.dll in coreclr when publishing jobs to Helix.

**Comment by josalem** [comment]
As far as I'm aware, this should already be available as a pacakge on the NuGet feed that Arcade puts its build outputs in (based on [this doc](https://github.com/dotnet/arcade/blob/master/Documentation/HowToCreatePackages.md)).  It should be in the dotnet-feed NuGet feed.

**Comment by echesakovMSFT** [comment]
@josalem Thanks!

**Comment by josalem** [comment]
Is this issue needed anymore?  I think the work above was completed a long while ago.

**Comment by ViktorHofer** [comment]
Thanks, closing.
