### ISSUE TITLE
Release Pipelines are sufficient to ship .Net Core 3.0 for Go Live (P7): Servicing/internal dependency flow and YAML stages

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1824]
This epic is done when:
- [x] Release flow works for both public and private (internal) builds
- [x] Release pipelines are converted to YAML-based pipelines
- [x] Arcade-* repos are on-board in YAML pipelines
- [x] Be able to publish stable packages using YAML pipelines
- [x] Target feeds are determined based on Channel+AssetCategory

Dates:
- Code complete by 06/19
- Prod deployment by 06/19 - 06/20
- Testing against PROD 06/20 - 06/25
- If needed, last PROD deployment 06/25 at the latest. All bug fixes between 06/20 and 06/25 will be tested against INT so we only deploy to PROD once

**Comment by JohnTortugo** [comment]
I think this epic can be closed. /cc @markwilkie @jcagme

**Comment by markwilkie** [comment]
Doesn't the setup packages to blob storage capability need to be in?

**Comment by JohnTortugo** [comment]
I'm not sure which issue you mean here. /cc @riarenas ?

**Comment by markwilkie** [comment]
hooray!
