### ISSUE TITLE
Helix reliability is high

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#1945]
- [x] Unifying services under single infrastructure (Service Fabric)
- [x] Ready for GitHub query parameters authentication deprecation
- [ ] Scenario test running

Non-Goals:
- Increased performance (identify metrics)
- Enable local dev workflow (Jared Parson's PoC)

Dev Workflow Benefits:
- Can get to logs faster in the AzDO UI

### @ChadNedzlek
- [ ] Work on service fabric health reporting

### @alexperovich 
- [ ] Porting API's to core 
- [ ] Work with David as needed

## Rough Timeline
  - arcade-services to .NET Core 3.1 : Done
  - improve testing of arcade-services : Done
  - dotnet-helix-services to .NET Core 3.1 : Done
  - improve testing of dotnet-helix-services : Done
  - all helix api versions ported: Done, not deployed or used in production yet
  - cloud-services to service fabric : Done, not deployed to production yet
  - generic service fabric health reporting : 8/10

**Comment by ChadNedzlek** [comment]
Epic epic complete!

**Comment by markwilkie** [comment]
Hooray!!!!!
