### ISSUE TITLE
Signing Package Ready for Consumption

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#226]
A signing package is needed that can be consumed by participating repos to sign their packages.  

This epic is considered complete when:
- [x] The signing package is defined and spec'd
- [x] The package is building and publishing
- [x] The package is adopted by Arcade and samples
