### ISSUE TITLE
Automated scenario testing for Maestro++/Darc

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#2340]
This epic tracks adding automated validation to Arcade-Services

Stage 1: Set up infrastructure and P0 tests (4/12)

* [x] The scenario tests run as part of every Arcade-Services deployment to prevent unexpected breaking changes reaching production.
* [x] Channel management tests
* [x] Adding builds to channels (including default channels) without a release pipeline
* [x] Adding builds to channels that have a release pipeline associated
* [x] General dependency flow with non-batched subscriptions
* [x] Dependency flow with coherency
* [x] Dependency graph generation

Stage 2: P1 tests (4/19)
* [x] Auto-merging of PRs (respecting the various available policies)
* [x] Batched subscription updates.
* [x] Arcade dependency flow (We do enough special logic when it's a dependency update from Arcade that it merits its own set of tests)
* [x] Darc add-subscription interactive flow

Stage 3: Additional validation (Post 4/19)
* [ ] Packages generated by Arcade-Services have automated validation before being pushed to the general use channels. (lower pri, no one is subscribed to arcade-services so they won't get automatically broken by a bad update)

**Comment by riarenas** [comment]
I believe this first push to get validation in place is completed. As we keep adding new functionality we just need to remember to add to the tests. (we've been pretty good at that so far)

There are some improvements that I can think of about how we report the test results, but I don't think it needs to be part of this epic.
