### ISSUE TITLE
Product KPIs (PKPIs)

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2778]
Product KPIs are measures of the product and its constituent parts that help determine health and drive action towards a healthier ecosystem.

Specific PKPIs are described here: https://github.com/dotnet/arcade/blob/master/Documentation/ProductKPIs.md

When this epic is done:
- [ ] The product KPIs listed in the document will have been implemented
- [ ] Repository owners and management will be able to query and/or view the PKPIs over time (where appropriate) in BARViz/Darc (darc may be only 'point in time').
- [ ] Repository owners and management can use the PKPIs to ensure that the product can iterate and ship quickly with high quality by identifying problem areas early and often.

/cc @shawnro @markwilkie @Chrisboh 

| Date  | Issue | Owner | Notes |
| ------ | ----- | ------- | ------- |
| Done | [Dependency updates that fail to flow seamlessly](https://github.com/dotnet/arcade/issues/4014) | adiaaida ||
| Done | [Number of dependency updates per given time frame](https://github.com/dotnet/arcade/issues/3907) | adiaaida ||
| Done | [Official build pass rate](https://github.com/dotnet/arcade/issues/2787) | epananth | |
| Done | [Official build time](https://github.com/dotnet/arcade/issues/2786) | epananth ||
| Done  | [Dependency staleness](https://github.com/dotnet/arcade/issues/2782) | chcosta ||
| Done  | [Existence of product dependency cycles](https://github.com/dotnet/arcade/issues/3905) | adiaaida ||
| Done | [Disabled subscriptions](https://github.com/dotnet/arcade/issues/4023) | meganaquinn ||
| ~10/21~ ~10/28~ ~11/5~ ~11/13~ 11/19 | [Official build time goal lines](https://github.com/dotnet/arcade/issues/4101) | epananth | Add ability to define per repo goal lines for build time |
| 11/18 | [PKPI documentation](https://github.com/dotnet/arcade/issues/4077) | epananth ||
| Done| [Official build time worst case scenario](https://github.com/dotnet/arcade/issues/4103) | epananth ||
| Done | [Update official build time report to use buildchannel insert time as end time](https://github.com/dotnet/arcade/issues/4116) | adiaaida ||
| ~10/30~ ~11/19~ 12/14 | [Longest build path visualization](https://github.com/dotnet/arcade/issues/4225) | adiaaida | Unexpected FR duty, partial PR available, redesign |
| ~11/1~ ~11/6~ 11/22  | [Split subscriptions view into product and toolset](https://github.com/dotnet/arcade/issues/4138) | meganaquinn | In PR |
| ~11/6~ 11/22 | [Superfluous input subscriptions](https://github.com/dotnet/arcade/issues/3906) | meganaquinn | In PR |
| ~11/13~ ~11/6~ 11/22 | [Conflicting input subscriptions](https://github.com/dotnet/arcade/issues/2801) | meganaquinn | In PR |
| done | Review dashboard, validate data | chcosta ||
