### ISSUE TITLE
Releases are quick and have high confidence

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2891]
(For follow-up work from this epic, please see https://github.com/dotnet/arcade/issues/6418 )

Create a process which implements the concept of rings and promotion taking on account v-team whiteboard talks. 

Main goal is to make the release process as straight forward and hands free as possible providing confidence that the product's quality is warrantied on each stage by testing and validation.

Details and ring definition [here](https://github.com/dotnet/arcade/blob/master/Documentation/ReleaseRingsPlan.md)

Also:

![image](https://user-images.githubusercontent.com/28021475/81864460-85d4da00-9521-11ea-8cdd-3417dff8b82f.png)

This epic is done when:
- [x] Tools to help automate the release preparation exist
- [x] There is a unified CLI for performing any release related automation and validation
- [x] Define each ring's scope and the tasks which compose them along with validation approaches
- [x] Understand what it means to move the release pipeline to YAML
- [x] Specify promotion condition/gates
- [x] Contracts are defined for each ring
- [x] Release time can be tracked and measured
- [x] Promotion is required and tied to a contract validation
- [x] Build ring is complete and part of the release pipeline*
- [x] Validation ring is complete and part of the release pipeline*
- [x] Staging ring is complete and part of the release pipeline*
- [x] Overall testing for CLI
- [x] Sync with stakeholders about ownership during the release
- [x] Document overall release process 
*Completion for these include: documentation, contract validation, tasks, tasks validation and outputs specification

Deliverable | Date | Notes
----------- | ---- | -----
Understand RP to YAML | 3/18 | Done
Rings definition and planning | 3/20 | Done
Promotion condition/gates | 3/20 | Done
Contracts definition | 8/14 | Done.
CLI with initial functions | 4/3 | Done
Prep ring | 4/10 | Done
Validation ring | 8/21 | Done
Staging ring | 6/4 | Done
Promotion is required | 8/1 | Done
Testing | 11/4 | Done
Sync with stakeholders | 9/24 | Done
Documentation | 9/24 | Done

**Comment by markwilkie** [comment]
@jcagme - can you add a link to the ring doc please?

**Comment by jcagme** [comment]
Added to the description
