### ISSUE TITLE
Release / Servicing features for .NET Core 3.0 GA

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#2935]
Work items required for releasing and servicing .NET Core 3

This epic is complete when:

* [X] All product repos are using the YAML stages infrastructure for publishing.
* [X] The infrastructure is enough to produce a stable build of the product, and validated by producing a stable release.
* [x] The infrastructure is enough to produce a servicing release of the product, validated by producing an internal servicing release.
* [x] Publishing documentation is up to date.
* [x] Successfully shipped two servicing releases (one must be internal).

**Comment by markwilkie** [comment]
@riarenas / @mmitche  - when should we close this?

**Comment by riarenas** [comment]
We still need to fulfill the three undone checkboxes:

* Update the docs (I should be able to get through this after leaving FR)
* We finish shipping the internal servicing release

**Comment by JohnTortugo** [comment]
@riarenas - Is the documentation the last remaining work here?

**Comment by riarenas** [comment]
Pretty much.

**Comment by JohnTortugo** [comment]
Just merged the documentation. \o/

**Comment by riarenas** [comment]
That marks all the checkboxes and I moved the two remaning issues to the current epic as they were either blocked or required further thinking.

Closing!
