### ISSUE TITLE
Generic mirroring/merging service

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3650]
We need to invest in a generic mirroring and merging service.  The existing Maestro based service has poor telemetry, poor error notification, and is very opaque.  This is also a common problem that could be deployed in a generic fashion for various teams to use.

I am thinking of a system with two primary pieces:
- A web frontend for configuration and status viewing
- A backend for performing merges.

This system should view all the merges and mirrors in a very generic fashion. They are all the process of moving code from `repoA@branchB->repoC@branchD`, where `->` represents a merge method.  In this context:
- Mirroring between a two repositories with identical branch names means `branchB` and `branchD` are the same branch, but `repoA` and `repoC` are different, and `->` represents a fast-forward.
- An inter-branch merge on the same repo would be a case where `repoA` and `repoC` are the same, but branchB and branchD are different, and `->` allows a recursive merge.

In this context, the system consists of:
- A trigger (e.g. new commit or time-based check)
- A mapping
- A merge method
- A process by which the results of the movement are expressed (e.g. direct commit or PR)
- A notification/status process

When done with this epic:
- [ ] The service should allow for arbitrary mappings of branches/repos
- [ ] The service should support webhook and time based triggers.
- [ ] The service should allow for direct submit of results as well as pull requests
- [ ] Source and target should be able to be GitHub or AzDO
- [ ] Telemetry should be in place to track failure rates and other key stats.
- [ ] A website should allow for configuration, show status
- [ ] Multiple teams/github orgs/azdo orgs should be able securely to use the system with separate permissions (e.g. a team working on the nuget.client team could restrict viewing of their status to only those users they wish to authorize).  There is no reason for a generic system to require multiple deployments

**Comment by dougbu** [comment]
Capturing a few lines from a Teams conversation that might be helpful later:
> maybe what you do is simply poll every ~~10~~ 5 minutes or something like that, and get webhooks

> https://developer.github.com/v3/repos/branches/#list-branches

> On the branch name thing, I think you'd configure the system to have a top level configuration for all repos, then specialize per repo as needed.  For example: "Mirror all master and release/* branches, as well as all protected branches"

----
Idea of a knob that just special-cases protected branches sounds wonderful because it should simplify the configuration. And, this would reduce duplicate configurations (be more DRY) e.g. the overlap between dotnet/versions and ASP.NET Core's protected branches.

**Comment by mmitche** [comment]
> Idea of a knob that just special-cases protected branches sounds wonderful because it should simplify the configuration. And, this would reduce duplicate configurations (be more DRY) e.g. the overlap between dotnet/versions and ASP.NET Core's protected branches.

Yeah, agreed.

**Comment by markwilkie** [comment]
After further discussion and good in put from @mmitche, it seems this epic is likely never going to have the priority it needs  - and the value is growing increasingly suspect.
