### ISSUE TITLE
Branch for net5

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#3818]
This epic is considered complete when:
- [x] net 3 is branched off 
- [ ] net 3 is setup for servicing
- [x] master is versioned to 5
- [x] darc is updated such that net 5 builds

**Comment by mmitche** [comment]
All but the servicing is totally complete at this point.

**Comment by JohnTortugo** [comment]
@mmitche - This is now complete, right?

**Comment by mmitche** [comment]
Yes
