### ISSUE TITLE
Publishing and Dependency Flow for NET5

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#3819]
This epic is complete when:

* [x] Infrastructure is sufficient to ship .NET 5.
* [x] Infrastructure is sufficient to service .NET 5. (.net 5 servicing exercise underway)
* [x] Publishing is no longer tied to the repository's arcade version.
* [x] There is general high confidence that the dependencies updated to what's expected
* [x] There is general high confidence that the published bits are what's expected
* [x] Dependency flow and publishing documentation is up to date.
* [x] All usage of release pipelines is removed from the dependency update and channel assignment flow.
* [x] Sufficient telemetry in place to measure success on an ongoing basis.
* [x]  All dotnet/* repos which are necessary for RedHat to build .NET 5 are using dependency flow

**Comment by riarenas** [comment]
**Week of 3/23:**

**@epananth:**

---

**@johntortugo:**

---


**@mmitche:**

---

**@riarenas:**
* Get final approval on the plan in https://github.com/dotnet/core-eng/pull/9218
* Finish creating issues related to the new flow 
* Start working on prototype for the service that will trigger official builds.
* Help Sunanda with this week's deployments.

FYI @markwilkie

**Comment by markwilkie** [comment]
Moving "the list" to the top

**Comment by riarenas** [comment]
Closing notes:

**In the area of publishing**, we delivered version 3 of the shared infrastructure based on the packages and templates provided by Arcade. This current version provided the following advantages over its predecessors: 
* Introduced performance improvements to the infrastructure, which reduced the publishing time for the repos in the product’s critical path (runtime, aspnetcore, sdk, installer) from ~130 minutes to ~22 minutes.
* Completely removed our dependency in the Azure storage based NuGet feeds that we had to manage ourselves, in favor of Azure artifacts feeds.
* Improved the reliability of publishing, as well as the diagnosability of failures during the process by removing our reliance on deprecated UI-based release pipelines in favor of using a config-as-code YAML based pipeline under source control.
* It’s centralized around a single pipeline that performs the publishing for every repo, bringing the advantage that changes to the publishing package or templates does not require the product repositories to take an arcade update, and consolidated the number of YAML stages that repositories had to add to their build from one stage per available publishing channel, to a single stage overall. 
* Added a Darc command  to easily trigger the publishing phase of a build that has already completed, for scenarios where a build needs to be assigned to different channels at different points in time.

**As for the dependency flow space**, we continued to improve Maestro++ and Darc in several areas:
* Maestro stopped using comments to convey the auto-merge status of PRs in favor of using GitHub checks.
* Introduced support to update .NET tool dependencies produced by repos.
* The coherency calculation algorithm was reworked such that it reduced the number of unhandled edge cases and improved the confidence that the versions of dependencies across the stack were correct.
* Added a component in Maestro++ that opens issues in core-eng whenever there are failures to open a dependency update PR. Most notably this allowed us to diagnose and fix long standing reliability issues coming from our external dependency on Azure DevOps and GitHub, and to engage with customers about problems they may have introduced in their dependency files.
* Addressed customer concerns about Maestro’s support for flowing NuGet feeds during the final product stabilization phase by reducing the amount of merge conflicts from dependency update PRs, and introduced a mechanism to dynamically clean up packages from temporary feeds that have already been released to nuget.org or our internal feeds to minimize the chance of package collision during restores.  

**In the future, we have our eye on additional improvements to both spaces**:
* Introduce the option to not require a PR before merging dependency updates to improve the end to end build times for servicing releases. This work was originally slated to be part of this epic, but was put on the back-burner in its own epic. 
* Port the latest publishing infrastructure to the .NET 3 servicing branches so they can take advantage of the improvements introduced during the .NET 5 timeframe. 
* Currently, we only host NuGet packages in Azure Artifacts. There have been asks to enable shared infrastructure that can publish other types of artifacts such as NPM and Maven packages to the feeds.
* Improve the visibility of pull requests and build failures caused by dependency updates with better notification mechanisms.
