### ISSUE TITLE
Native tools bootstrapping via Arcade is useful to enable our toolset policy

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4072]
- [x] Guidance is updated and enables https://github.com/dotnet/arcade/blob/master/Documentation/Policy/ToolsetPolicy.md
- [ ] Native tools bootstrapping is conditional by OS
- [ ] Works well in a Docker container as well
- [ ] Won't re-install if already available

======================================

Originally from @dougbu ; basically the ASP.NET Team needs tar for Windows, which we lost in a Windows Client SKU version snafu.   

ASP.NET has made a workaround for now, but there remains no way to have a tool dependency in the global.json that is only for builds on a specific OS, so for any team that has a native dependency they'd like to bootstrap that only applies to one of three of the main OS choices, we don't really have a story for these folks.

Simplest thing to do is likely to have some kind of property in said JSON with an OS check, but there could be nicer ways to do it. 

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [ ] https://github.com/dotnet/arcade/issues/64
- [x] https://github.com/dotnet/arcade/issues/833
- [x] https://github.com/dotnet/arcade/issues/2248
- [x] https://github.com/dotnet/arcade/issues/2674
- [ ] https://github.com/dotnet/arcade/issues/4482
- [x] https://github.com/dotnet/arcade/issues/4780
- [x] https://github.com/dotnet/arcade/issues/4786
- [x] https://github.com/dotnet/arcade/issues/4787
- [ ] https://github.com/dotnet/arcade/issues/4788
- [x] https://github.com/dotnet/arcade/issues/4790
- [x] https://github.com/dotnet/arcade/issues/4791
- [x] https://github.com/dotnet/arcade/issues/4792
- [x] https://github.com/dotnet/arcade/issues/4793
- [x] https://github.com/dotnet/arcade/issues/4795
- [ ] https://github.com/dotnet/arcade/issues/4822
- [x] https://github.com/dotnet/arcade/issues/5434
- [x] https://github.com/dotnet/arcade/issues/7327

**Comment by dougbu** [comment]
Thanks @MattGal❕

`tar` is a solid Windows-only example. We could have handled that by ensuring init-tools-native.cmd or init-tools-native.ps1 is invoked and only on Windows.

However the opposite case happens with tools such as the `nginx` reverse proxy. We need that everywhere _except_ on Windows.

**Comment by dougbu** [comment]
Ping. Any update on this issue?

**Comment by markwilkie** [comment]
@dougbu - do you think this warrants an increase in urgency?  We know it's a priority and needs to be done - but perhaps timing is important?

**Comment by dougbu** [comment]
Timing is important mainly w.r.t. https://github.com/dotnet/arcade/blob/master/Documentation/Policy/ToolsetPolicy.md. That doesn't have a deadline I'm aware of but let's avoid a mad rush once it does. The earlier we unblock relying on Arcade for more tools, the smoother things will go.

**Comment by markwilkie** [comment]
A fair point for sure, and I for one am in agreement.  I've converted this issue to an epic to make sure this is prioritized sooner than later.

**Comment by chcosta** [comment]
Rough costing

Major issues:
-	[Permit defining native tools installation / OS](https://github.com/dotnet/arcade/issues/2673)
o	Cost: 2 - 8 weeks
o	The SWAG here is pretty large because the implementation will require a rewrite of native toolset bootstrapping.
	2 - 4 weeks – define a rid model like https://github.com/dotnet/runtime/tree/master/src/libraries/pkg/Microsoft.NETCore.Platforms.  The pain point here is figuring out how to parse the model using our current design which is Powershell (Windows) or Bash (Linux) and supporting it in both places.  XML parsing is notoriously difficult in Bash.  The simplest solution (2 weeks) is to just bake the rid graph for all OS / distros into the bash rather than trying to parse a common graph model file.
	8 weeks - It doesn’t really make sense for us to write our own rid graph fallback model.  The original implementation went the direction of using powershell / bash because the languages are simple and readily available on all OS/distros including those not yet supported by .NET Core.  I think unsupported platforms are less of a concern now than they were in the past and we should optimize for platforms supported by .NET Core.  We should rewrite native toolset bootstrapping to acquire the dotnet CLI, and use the CLI for things like OS versions (https://github.com/dotnet/runtime/tree/master/src/libraries/pkg/Microsoft.NETCore.Platforms).  We would still need some shim scripts to acquire the CLI, but otherwise we can use a single code base (this would also address https://github.com/dotnet/arcade/issues/2674).  
-	[Don't install tools that are already available](https://github.com/dotnet/arcade/issues/4780)
o	Cost: 2 – 4 weeks
o	I see a couple obvious solutions with different costings
	2 week solution - Simplest solution is to implement some more rigor around a tool artifact so that we can associate version discovery for a tool, its default install location, etc… so that we can discover tools in default locations or in the path and then do version matching.  Then we can do non-exact matching for dev mode builds and exact version matching for ci builds.
	2 week solution – I hear there is some version matching we are already doing for artifacts w.r.t. os onboarding, we could investigate re-using that logic
	4 week solution – One [proposal](https://github.com/dotnet/arcade/issues/4780#issuecomment-583516545) is to require native tools are run in contains.  It would take some time to figure out what this would look like, generate containers, wire it in to the builds, figure out how this would be handled (or ignored) on Mac

**Comment by jonfortescue** [comment]
Kicked a few things to triage but most of these could just be closed. Closing the epic now.
