### ISSUE TITLE
.NET Core dependency update management

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#434]
In .NET Core 3, dependency updates are done in the following way:

repo build -> tagged to channel (build purpose) -> downstream repo declares they take assets from channel+repo combo -> Maestro++ updates downstream repo's target branch

Because of the large number of branches expected in the .NET Core 3 workflow (e.g. stabilized builds, private builds, speculative flow builds, etc.) we need good channel/subscription management.  This also ties into branch managment

This epic will be done when:

- [x] Builds can be assigned to channels automatically or manually
- [ ] Channels can be created by developers/shiproom/repo owners for various purposes (e.g. private build), potentially automatically creating new subscriptions, branches, etc.
- [ ] Channels can be created automatically by tooling for short-lived scenarios (e.g. speculative version flow)
- [ ] Existing channels/subscriptions can be managed (e.g. pruned, queried, changed)

**Comment by markwilkie** [comment]
@mmitche - should this epic be closed now that we're tracking elsewhere?

**Comment by markwilkie** [comment]
Basic functionality is in place, and the check boxes above are tracked via other epics.  Closing.
