### ISSUE TITLE
.NET Core 3.0 Mission Control

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#436]
Mission Control should be able to represent .NET Core 3 product state. This epic is complete when:

- [ ] The state of various repository builds, based on their output channel, is visible
- [ ] The state of various repository tests, based on their output channel, is visible
- [ ] The state of the dependencies at the referenced versions is visible (test results, 'oldness')

**Comment by mmitche** [comment]
Already covered by: https://github.com/dotnet/core-eng/issues/3728
