### ISSUE TITLE
Arcade building and publishing in the open

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#45]
We'll consider this portion of the work "done" when Arcade is:
- [x] Enabled in CI for all supported platforms
- [x] Building and signed officially for all supported platforms
- [x] Publishing 
- [x] Repo is no longer private and has all the appropriate licenses
- [x] "Getting Started" documentation is available
- [x] Package tests are in place to give some confidence

**Comment by chcosta** [comment]
Waiting for https://github.com/dotnet/arcade/pull/81 before publishing an official build from the repo.

**Comment by chcosta** [comment]
Official build packages are published to feed
