### ISSUE TITLE
Remove Release Pipeline Runner (RPR)

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4577]
This issue is complete when:

- [ ] Have a way to promote builds to channels after the fact (Investigate use the `post-build.yml` to create a new build pipeline). [Issue here](https://github.com/dotnet/arcade/issues/4601).

- [ ] Point ChannelReleasePipeline to the empty release pipelines. [Issue here.](https://github.com/dotnet/arcade/issues/4602)

- [ ] BuildChannel should be assigned when the assets are published. BuildChannel creation should be decoupled from Build creation. [Issue here.](https://github.com/dotnet/arcade/issues/4603)

- [ ] Remove need of PublishUsingPipelines from Arcade SDK. [Issue here](https://github.com/dotnet/arcade/issues/4604) and [here](https://github.com/dotnet/arcade/issues/3597).

- [ ] Remove PublishUsingPipelines from the Publish Metadata to BAR task. [Issue here.](https://github.com/dotnet/arcade/issues/4630)

- [ ] Remove RPR triggering instructions in Maestro.Web -> Startup.cs. [Issue here.](https://github.com/dotnet/arcade/issues/4631)

- [ ] Remove ReleasePipeline associated Maestro API. [Issue here.](https://github.com/dotnet/arcade/issues/4643)

- [ ] Remote RPR service fabric service. [Issue here.](https://github.com/dotnet/arcade/issues/4644)

- [ ] Update BAR Model to remove ReleasePipelines related entities/properties. [Issue here.](https://github.com/dotnet/arcade/issues/4645)

- [ ] Delete RPR related files in eng/common. [Issue here.](https://github.com/dotnet/arcade/issues/4646)

/cc @mmitche @riarenas - I'll create issues for the topics above. Also, I could swear there was an issue to track this work.. but I couldn't find it anywhere.

**Comment by JohnTortugo** [comment]
Changing the status to _Breakdown_ while I work on the list of all issues that have to be worked on and the best order to address them.

**Comment by JohnTortugo** [comment]
Testing. Ignore.
