### ISSUE TITLE
Moving entirely to AzDO package feeds

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#4609]
Business objectives:
- [x] dotnet.myget.org is deprecated
- [x] All feeds used by .net5 are hosted by AzDO
- [x] All feeds used by .net core servicing (2.x and 3.x) are hosted by AzDO

Full write-up:  https://github.com/dotnet/arcade/pull/4555

Plan:
- Investigate and broadly socialize this plan with product teams to both set expectations, and catch any gaps. (end of Jan 2020)
- Make all MyGet feeds read-only (first part of Feb)
- Bulk load a new ‘legacy’ feed in Azure DevOps from the existing MyGet feeds (end of April)
- Turn off MyGet (first week of March)
- Finish cleaning up (May)

---

Week of May 11 goals (for @garath):

 - Make safe or at least have a plan for the service builds
