### ISSUE TITLE
Improve customers experience  by having additional diagnostic options

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#5132]
Currently there's an effort by Dan M and David Fowler to enable dumps for all the scenarios on all platforms.  This epic is to take that work and "normalize" it so that it becomes shared infra.

- [ ] Dump capture is part of the shared infra
- [ ] Dump retrieval is part of the shared infra

New content: 

We have been receiving feedback from out customers that have more diagnostic options available and making them easier to access. One of the efforts in this space was to enable dumps for all the scenarios on all platforms (effort by Dan M and David Fowler).  In addition to the efforts around dump files, there have been several other areas that have been added recently where we can contribute to having a shared infrastructure 

## Business Impact

- [ ] Reduction in the number of developers that say they need more diagnostic options within our quarterly satisfaction

## Goals 
- [ ] Make dump files available across all supported platforms
- [ ] Provide a shared infrastructure that can be used to diagnose failures

**Comment by markwilkie** [comment]
closing in favor of https://github.com/dotnet/core-eng/issues/12471
