### ISSUE TITLE
Packaging package is ready for consumption

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#556]
This epic is considered complete when:

- [ ]   The package is defined and spec'd
- [ ]   The package is building and publishing
- [ ]   The package is adopted by at least 2 tier 1 repos.

**Comment by markwilkie** [comment]
This turned out to be guidance only.  Closing
