### ISSUE TITLE
Provide coherent guidance to our customers

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#573]
Most of our services/tools are reasonably well documented.  However, it's sometimes tough to find what's needed, and there are limited "samples" or "tutorials" that can be followed.

This epic should be considered complete when:
- [x] A dev can find guidance and documentation for the area/s he's interested.  (see below for the list)
- [x] A FAQ exists, and is consistently updated - plus, it supports crowd updates.
- [x] A dev is able to follow the guidance to move the CI build to Arcade
- [x] A dev is able to follow the guidance to onboard a repo to Arcade
- [x] A dev is able to find documentation on all packages published as part of the Arcade SDK
- [x] A dev is able to follow guidance on how to use eng svcs web services
- [x] A dev is able to follow the guidance for how to run test through helix
- [ ] A dev is able to follow the guidance for how to use OS Onboarding  (this feature is not complete, and thus is not checked)

**Comment by markwilkie** [comment]
Hooray!  (closing)
