### ISSUE TITLE
Unify and improve build publishing across .NET (6.0/5.x/3.x)

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5789]
<del>The 3.x version version of arcade should move to using the v3 publishing. This will allow the addition of new channels without rolling out new arcade versions, as well as unifying publishing. When complete:
</del>
<del>
Backporting work:
</del>

<del>
- [ ] Remove legacy publishing code from arcade main
- [ ] Arcade 3.x will produce and use v3 publishing by default.
- [ ]  Remove legacy publishing code from arcade release/3.x
- [ ]  Remove legacy publishing code from arcade release/5.x
- [ ] All arcade 3.x repos will have moved to v3 publishing. (Repos and Branches that take arcade updates from 3.x will move to V3 publishing)
</del>

Improvements/Additions:
- [x] Improve publishing performance, make the  Eg: downloading the assets using Azure API instead of downloading the entire folder, adding parallelism to artifacts and symbols publishing which makes the whole process faster
- [x] Update tests and documentation 
<del>
- [ ] Improve Symbol publishing performance. Eg: Should stop publishing Symbols to nuget feed instead, forcing all the symbol packages to have non-stable versions. 
- [ ] Add support for publishing vssdk/vs-impl artifacts
</del>

**Comment by tkapin** [comment]
Unassigned myself per the last LT epic review.

**Comment by epananth** [comment]
Backporting work is moved to a different epic -> https://github.com/dotnet/arcade/issues/7431 

So closing this epic.
