### ISSUE TITLE
Test projects running on Helix supported

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#580]
This epic is considered complete when:
- [x] Sufficient functionality is available in Arcade via package/s to submit work to Helix
- [x] The results are published as expected
- [x] Guidance/Documentation is available

**Comment by markwilkie** [comment]
@MattGal and @alexperovich as an FYI

Also, it's good to note that there is already some limited functionality in Arcade today, but additional work is needed for wide adoption.

**Comment by alexperovich** [comment]
The basic functionality is here https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.Helix/JobSender for C# and https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.Helix/Sdk for MSBuild. I will add a short readme to the MSBuild stuff.

**Comment by jonfortescue** [comment]
Considering closing this epic and moving the documentation requirements over to #947. Does that sound fine @markwilkie?

**Comment by markwilkie** [comment]
ACK
