### ISSUE TITLE
Developer Workflow

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#5871]
The business objectives will assuredly increase, but for now we know at least this one:

- [ ] Dumps are automatically captured and viewable for both hangs and crashes on all platforms in the .net5 timeframe  (more work should be done during .net 6 to make this more shareable - e.g. part of Arcade/Helix)

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [x] https://github.com/dotnet/core-eng/issues/6771
- [ ] https://github.com/dotnet/arcade/issues/5651
- [ ] https://github.com/dotnet/arcade/issues/6025
- [x] https://github.com/dotnet/core-eng/issues/10661
- [ ] https://github.com/dotnet/arcade/issues/6636
