### ISSUE TITLE
Improve Dev WF by making PR results actionable

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#5963]
### Motivation and Business Impact
The north star of this epic is to improve the developer workflow by focusing on making the PR results accurate and actionable.  'Red' should mean that the dev can (and should) fix something, and 'Green' should mean that the change is good. 

Today, it can be tough to figure out what the actual root problem is, compounded by periodic infrastructure outages and/or transient issues that are outside of the devs control.  When "bad actor" tests are added, it becomes clear why we as devs are frustrated with seemingly "never" getting a green PR.

Jared Parsons wrote a great doc that much of this thinking came from:   [Resiliency in our infrastructure.docx](https://microsoft-my.sharepoint.com/:w:/r/personal/jaredpar_microsoft_com/_layouts/15/guestaccess.aspx?e=0nRQWy&share=EfdbxSdPRKdKnYTd84gxdeUBYuB5AYiKVcbTQcXP2SdzdQ)

To follow the conversations, check out our V-Team's Teams Channel which is where you should be able to find most of the context.

### Business Objectives
- [x] The dev knows what action to take regarding the failures in their PR.  
- [x] PR results are resilient to transient issues 
- [x] Clear visibility to which failures need attention at more of a macro level (allows leads to reason about where investments need to be made) 
- [x] Known Issues/outages do not result in unactionable PR results 
- [ ] ~Improve MSPoll values around engineering, specifically engr107 and engr108~ (survey values no longer available)

### Functional Deliverables
- [x] Configurable retries for tests to allow passing PR’s even with flaky tests 
- [x] Configurable retries for builds to allow passing PR’s even with intermittent infrastructure issues 
- [x] Failing PRs indicate what is failing to the user
- [x] Every build includes a best effort highlighting of most relevant failures in a single place, with deep links 
- [x] Customers have a way to query on test results to determine which tests are behaving abnormally (e.g. failing more often than usual
- [x] Ongoing outages or known issues that affect the PR are made known to the dev (e.g. including a link to the outage/known issue) 
- [ ] ~Stretch goal: When a persistent outage is resolved, PRs are updated~

### Deliverables for Engineering
- [x] Ensure monitoring and alerting coverage on all services created for this epic and address any outstanding alerts from monitoring before closing the epic.
- [x] Comprehensive documentation (including architectural diagrams where necessary) for engineering hand-off. 

### Metrics for Success

Where applicable, metrics should be sliceable by repo. 

#### User Feedback

- [x] Customer feedback from the sentiment tracker is tracked via a GitHub issues and the customer agrees with the next steps.
- [x] Stretch Goal: NPS-style question on Customer Survey (best effort to get feedback from customers on this) and/or Sentiment Feedback widget to gauge customer satisfaction with the feature. **A goal of 7 or higher** would be favorable. 
    - Results from the March 2023 .NET Engineering Services Satisfaction Survey
        - Build Analysis (Unique build/test failures): 8
        - Automatic Build Retries: 9.25
        - Automatic Test Retries: 8
        - Known Issues - 8.33

#### Usage
- [ ] **Less than 10%** of Pull Requests are "merged on red" 
    - [Link to data](https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/8bdd4339-ea39-4e67-963a-fc44a450605b/ReportSection?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47), see "Merge on Red Trend"
    - Between Jan 2023 and March 2023: max of 28%, min of 16%
- [x] Build Result Analysis should be viewed **at least 60% of the time** on failing Pull Requests
    - [Link to data](https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/e6deb422-46fc-4f80-8892-ba7036081986/ReportSection)
    - Between Nov 2022 and March 2023: max of 62%, min of 27%

### One-Pagers: 
- [Retry Tests](https://github.com/dotnet/core-eng/blob/master/Documentation/Project-Docs/Dev%20Workflow/Retry%20Tests%20-%20arcade5963.md)
- [Retry Builds](https://github.com/dotnet/core-eng/blob/master/Documentation/Project-Docs/Dev%20Workflow/Retry%20Builds%20-%20arcade5963.md)
- [Failure Guessing](https://github.com/dotnet/core-eng/blob/master/Documentation/Project-Docs/Dev%20Workflow/Failure%20Guessing%20-%20arcade5963.md)
- [Known Issues](https://github.com/dotnet/core-eng/blob/master/Documentation/Project-Docs/Dev%20Workflow/Known%20Issues%20-%20arcade5963.md)

------------------
### Notes
[Networking notes on keeping CI failures low](https://microsoft.sharepoint.com/teams/netfx/corefx/_layouts/15/Doc.aspx?sourcedoc=%7B0cfbc196-0645-4781-84c6-5dffabd76bee%7D&action=edit&wd=target%28Networking.one%7C7f7a68c9-55b6-465a-9c30-bab26b5f7d82%2FWeekly%20reports%7Cd6cb88b0-8794-4f03-bdda-f252c9da6522%2F%29)

---------------
## Milestones
- [x] Infra
  - [x] Set up test repos and AzDO instances that can plug into our webhooks
  - [x] Finish POC, make sure we have something working
  - [x] Determine success metrics. 
  - [x] CLI tools for testing/running things locally
- [x] Retry Tests
  - [ ] ~Setup: Migrate Helix scripts out of Arcade and into Helix. Deliverable: Customer functionality shouldn't change.~ Work was not necessary
  - [x] MVP: Re-run work item if error is detected that was configured in customer's configuration file (JSON). DataMigrationProcessor will need to understand that a retry occurred. (Reporting will rely on this). 
  - V2: none at this moment
- [x] Retry Build
  - [x] Setup: Need to verify that the existing infra can support this functionality. 
  - [x] MVP: Re-run build if error is detected that was configured in the customer's configuration file (JSON). Reporting will also need to know about this. Need to let customer know that we are doing this. 
  - V2: none at this moment
- [x] Failure Guessing 
  - [x] MVP: Wall-of-text of what AzDO spits out at us with links to the logs/console log page; maybe a link to the mock-up? 
  - [x] V2: Implement mock-ups to be real data that is published to the Build Result Analysis Summary checks page.
  - [x] V3: Iterate based on customer feedback (direct feedback; sentiment tracking data)
  - [ ] ~V4??: "Notifications"?? Comments on PR? Teams notifications?~
- [x] Outages/Known Issues
  - [x] November 2021 EOM: Include widespread issues in build analysis tab
  - [x] January 2022 EOM: Known issues matching PoC
  - [x] February 2022: Build analysis identifies build failures affected by known issues
  - [x] March 2022: Reporting shows impact of a known issue
  - [x] March 2022: Contributors can submit new issues using Build Analysis 
- [x] Quarantine Tests
  - MVP: To be determined
- [x] Test Reporting
  - [x] October 2021 EOM: Team approval on PR to turn POC into a Service Fabric service.
  - [x] November 2021 EOM: Test Reporting service stood up in staging. 
	- [x] Service in SF (with multiple instances) to ingest the shunted passing data into the AzureDevOpsTestsSummary table in Kusto (should run hourly) 
	- [x] Service to do calculations on the aggregated data in AzureDevOpsTestsSummary and AzureDevOpsTests tables (should run daily) 
	- [x] Create new service account user for AzDO for Dev WF 
  - [x] December 2021 EOM: Test Reporting service stood up in production.
	- [x] Must match set up in Staging 
	- [x] Ensure any new users or secrets are usable in Production 
  - [x] January 2022 EOM: Queries available for customers to use
	- [x] Chi-squared service calculating reliable data
	- [x] Queries in Kusto for reports available for customers to us
  - [x] June 2022 EOM: Test Results Clean-up
      - [x] Fix Chi-squared service (and remove `no truncation` band-aid)
      - [x] Decommission TestResults table
- [x] UX Improvements and customer-facing work (mid-July 2022)
    - [x] Address customer feedback
    - [x] Documentation for customers
    - [x] Evangelism of product to .NET org
    - [x] Create GitHub app/bot specific for Build Analysis
    - [x] UX user study with product devs
- [ ] ~Reporting for Repo Owners~ Replaced by Known Issues epic
  - [ ] MVP: Be able to report on flaky tests; quarantined tests; any test that didn't pass for any reason. Likely a dashboard in Power BI. 
  - [ ] V2: Make the results more actionable for the repo owners. (e.g. click a button and it opens an issue to investigate X test). 
  - V3: none at this moment

### Milestone 1
- Build Result Analysis Summary GitHub check available on Pull Requests (currently available in Arcade Services)

![image](https://user-images.githubusercontent.com/47990216/112220938-12413600-8be4-11eb-94a7-91b0f45ffdb2.png)

- Immediately viewable reports on tests and build failures, with deep links to Azure DevOps console logs and test results.
- Sentiment tracking for feedback from users. Feedback goes directly to dnceng, and we'll review it and use it to help drive design and prioritization. 

![image](https://user-images.githubusercontent.com/47990216/112220989-22591580-8be4-11eb-83ac-48d05140a389.png)

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [ ] https://github.com/dotnet/core-eng/issues/11576
- [ ] https://github.com/dotnet/core-eng/issues/11578
- [ ] https://github.com/dotnet/arcade/issues/6662
- [ ] https://github.com/dotnet/arcade/issues/6663
- [ ] https://github.com/dotnet/arcade/issues/6964
- [ ] https://github.com/dotnet/core-eng/issues/12221
- [ ] https://github.com/dotnet/core-eng/issues/12660
- [ ] https://github.com/dotnet/core-eng/issues/12683
- [ ] https://github.com/dotnet/core-eng/issues/12684
- [ ] https://github.com/dotnet/core-eng/issues/12692
- [ ] https://github.com/dotnet/core-eng/issues/12696
- [ ] https://github.com/dotnet/core-eng/issues/12702
- [ ] https://github.com/dotnet/core-eng/issues/12833
- [ ] https://github.com/dotnet/core-eng/issues/12906
- [ ] https://github.com/dotnet/core-eng/issues/12940
- [ ] https://github.com/dotnet/core-eng/issues/12972
- [ ] https://github.com/dotnet/core-eng/issues/13116
- [ ] https://github.com/dotnet/core-eng/issues/13142
- [ ] https://github.com/dotnet/core-eng/issues/13145
- [ ] https://github.com/dotnet/arcade/issues/7424
- [ ] https://github.com/dotnet/core-eng/issues/13189
- [ ] https://github.com/dotnet/core-eng/issues/13246
- [ ] https://github.com/dotnet/core-eng/issues/13262
- [ ] https://github.com/dotnet/core-eng/issues/13266
- [ ] https://github.com/dotnet/arcade/issues/7475
- [ ] https://github.com/dotnet/core-eng/issues/13314
- [ ] https://github.com/dotnet/core-eng/issues/13330
- [ ] https://github.com/dotnet/core-eng/issues/13333
- [ ] https://github.com/dotnet/core-eng/issues/13363
- [ ] https://github.com/dotnet/core-eng/issues/13413
- [ ] https://github.com/dotnet/core-eng/issues/13415
- [ ] https://github.com/dotnet/core-eng/issues/13449
- [ ] https://github.com/dotnet/core-eng/issues/13492
- [x] https://github.com/dotnet/core-eng/issues/13503
- [ ] https://github.com/dotnet/core-eng/issues/13536
- [ ] https://github.com/dotnet/core-eng/issues/13781
- [ ] https://github.com/dotnet/core-eng/issues/13800
- [ ] https://github.com/dotnet/core-eng/issues/13807
- [ ] https://github.com/dotnet/core-eng/issues/13862
- [ ] https://github.com/dotnet/core-eng/issues/13897
- [ ] https://github.com/dotnet/core-eng/issues/13983
- [ ] https://github.com/dotnet/core-eng/issues/14002
- [ ] https://github.com/dotnet/core-eng/issues/14055
- [ ] https://github.com/dotnet/core-eng/issues/14182
- [ ] https://github.com/dotnet/core-eng/issues/14258
- [ ] https://github.com/dotnet/core-eng/issues/14273
- [ ] https://github.com/dotnet/core-eng/issues/14357
- [ ] https://github.com/dotnet/core-eng/issues/14402
- [ ] https://github.com/dotnet/core-eng/issues/14527
- [ ] https://github.com/dotnet/core-eng/issues/14679
- [ ] https://github.com/dotnet/core-eng/issues/14680
- [ ] https://github.com/dotnet/core-eng/issues/14708
- [ ] https://github.com/dotnet/core-eng/issues/14710
- [ ] https://github.com/dotnet/core-eng/issues/14721
- [x] https://github.com/dotnet/core-eng/issues/14757
- [ ] https://github.com/dotnet/core-eng/issues/14794
- [ ] https://github.com/dotnet/core-eng/issues/14913
- [ ] https://github.com/dotnet/core-eng/issues/14915
- [ ] https://github.com/dotnet/core-eng/issues/15058
- [ ] https://github.com/dotnet/core-eng/issues/15059
- [ ] https://github.com/dotnet/core-eng/issues/15102
- [ ] https://github.com/dotnet/core-eng/issues/15118
- [ ] https://github.com/dotnet/core-eng/issues/15129
- [ ] https://github.com/dotnet/core-eng/issues/15157
- [ ] https://github.com/dotnet/core-eng/issues/15235
- [ ] https://github.com/dotnet/core-eng/issues/15269
- [ ] https://github.com/dotnet/core-eng/issues/15271
- [ ] https://github.com/dotnet/core-eng/issues/15294
- [ ] https://github.com/dotnet/core-eng/issues/15318
- [ ] https://github.com/dotnet/core-eng/issues/15321
- [ ] https://github.com/dotnet/core-eng/issues/15322
- [ ] https://github.com/dotnet/core-eng/issues/15324
- [ ] https://github.com/dotnet/core-eng/issues/15366
- [ ] https://github.com/dotnet/core-eng/issues/15387
- [ ] https://github.com/dotnet/core-eng/issues/15406
- [ ] https://github.com/dotnet/core-eng/issues/15453
- [ ] https://github.com/dotnet/core-eng/issues/15478
- [ ] https://github.com/dotnet/core-eng/issues/15484
- [ ] https://github.com/dotnet/core-eng/issues/15491
- [ ] https://github.com/dotnet/core-eng/issues/15494
- [ ] https://github.com/dotnet/core-eng/issues/15503
- [ ] https://github.com/dotnet/core-eng/issues/15512
- [ ] https://github.com/dotnet/core-eng/issues/15517
- [ ] https://github.com/dotnet/core-eng/issues/15542
- [ ] https://github.com/dotnet/core-eng/issues/15571
- [ ] https://github.com/dotnet/core-eng/issues/15572
- [ ] https://github.com/dotnet/core-eng/issues/15591
- [ ] https://github.com/dotnet/core-eng/issues/15559
- [ ] https://github.com/dotnet/core-eng/issues/15573
- [ ] https://github.com/dotnet/core-eng/issues/15631

- [ ] https://github.com/dotnet/core-eng/issues/15629

**Comment by tkapin** [comment]
@rokonec - please work with @ChadNedzlek to refine the Phase 1 business priorities into more detailed requirements so we can came up with a design proposal.

**Comment by ChadNedzlek** [comment]
Changed title to give "build" it's own epic.  Tests and builds are very different beasts when it comes to tackling them, because the quantity and quality of data is vastly different.

**Comment by markwilkie** [comment]
After our v-team discussion yesterday where it proved difficult to make forward progress, I'll give a hand to see if the discussion can be "jump started".  What I'll present should be thought of as a "starter fluid", not the actual "fuel".  Meaning.....the right approach is probably still "out there" - at least to a degree.  

Perhaps this proposed approach can be applied the the data we have to see how it does (or doesn't) bring value.

With that said, here are my "starter" thoughts:

**Action:** 
(1) Retry test on the same machine
**Criteria:**
- Test failed
- The last test run was successful

**Action:** 
(2) Retry test on the different machine
**Criteria:**
- Test failed
- The last test run failed when run on same machine (1)
- The test before last was successful

**Action:** 
(3) Fail test
**Criteria:**
- Test failed
- One of the following is true:
  - Actions (1) and (2) were failures
  - Tests have not been marked as chronically failing or as flaky (as those are dealt with separately)
  - Last (n) tests were failures
  - Specific test annotations (e.g. threshold, etc) result in marking the test as a failure

  **Action:** 
(4) Mark test as chronically failing, but not necessarily flaky
**Criteria:**
- Test failed
- Test has failed for the last (n) times

  **Action:** 
(5) Mark test as flaky
**Criteria:**
- Test failed
- The pattern shows the last (n) runs had (y) failures  (demonstrating a pattern of pass/fails)

  **Action:** 
(6) Skip test (don't run it at all)
**Criteria:**
- Tests are marked as chronically failing (4) or as flaky (5)

**Comment by ChadNedzlek** [comment]
There are some interesting investigations we can take that can help distill this starter fluid. :-).  Like what does it look like to run a test on the same machine... a different machine... how can we report that in a useful way to Azure Pipelines/something else so that we have the data we need to "do the right thing".

I have a feeling that maybe for non-PR builds, we run enough of them that maybe just always looking at the last N builds might be statistically good enough without having to retry a test within a single build (sort of treating the N+1 as, more or less, an implicit retry of the N build).  There were 6000 executions of every test in the last two weeks for runtime, for example... that's a ton of data that a 6001st test probably won't add much to. :-) That might save resources/complication, and help with reporting, since Azure Pipelines has some pretty good reporting around the analytics for a branch.  When it gets down to the wire of shipping, maybe that means we need to investigate 2-3 random failures for the build we want to ship... but we'd probably want to do that anyway, even if we deemed them "flaky and irrelevant".

**Comment by markwilkie** [comment]
I like the thinking Chad.  :)  Let's chat again and see what the right next steps are.

Cheers

**Comment by sunandabalu** [comment]
> I have a feeling that maybe for non-PR builds, we run enough of them that maybe just always looking at the last N builds might be statistically good enough without having to retry a test within a single build (sort of treating the N+1 as, more or less, an implicit retry of the N build). There were 6000 executions of every test in the last two weeks for runtime, for example... that's a ton of data that a 6001st test probably won't add much to. :-) That might save resources/complication, and help with reporting, since Azure Pipelines has some pretty good reporting around the analytics for a branch. When it gets down to the wire of shipping, maybe that means we need to investigate 2-3 random failures for the build we want to ship... but we'd probably want to do that anyway, even if we deemed them "flaky and irrelevant".

Makes sense for non-PR builds, to compare against previous builds in the same branch. For PR builds, the mechanism to identify whether a test is chronically failing  or is it flaky would require some sort of retry and bubbling up that info for reporting. We need to ensure the reporting structure can accomodate both, or way to demarcate the PR vs Non-PR if that is more convenient.

**Comment by sunandabalu** [comment]
>   **Action:**
>   (6) Skip test (don't run it at all)
>   **Criteria:**
> * Tests are marked as chronically failing (4) or as flaky (5)

For tests that are consistently failing need to be looked at and either turn the test off or mark it as flaky so we can skip it. Just blindly skipping a chronically failing test would mean sweeping it under the rug :)

**Comment by ChadNedzlek** [comment]
I'm not sure where the epic about getting everyone on a shared testing infrastructure... but any "retry" logic we write won't help anyone until that epic is complete.  Right now, everyone has implemented their own test execution framework, so any work would have to be hand written into every single repository, which isn't a good use of our time (since it would all get deleted when that other epic started up anyway).

We can make it work in arcade, assuming that will be the template for other teams test runs, since it's supposed to be the shared infrastructure place.  Or maybe we need to bump that other epic up a bit so that we've got a shared execution place that every repo uses that we can put the retry stuff in.

**Comment by ChadNedzlek** [comment]
Found it. It was epic #5132. But that lost the "centralize the testing infrastructure" part of it in the title, and I'm not sure if it's focused on that or if we need another epic? Or to do that here?

**Comment by missymessa** [comment]
WE'RE DONE!! Closing!!
