### ISSUE TITLE
Policy/guidance to have consistent versions of our tooling

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#61]
@dleeapho commented on [Tue Jan 31 2017](https://github.com/dotnet/core-eng/issues/404)

This is the second part of implementing cmake toolset.  This is mainly around uptake in the official builds.

---

@shawnro commented on [Fri Feb 03 2017](https://github.com/dotnet/core-eng/issues/404#issuecomment-277379717)

@dleeapho can you please link the first part of the work to this one?

---

@ravimeda commented on [Fri Feb 03 2017](https://github.com/dotnet/core-eng/issues/404#issuecomment-277380284)

First part that covers dev workflow is #224 

---

@ravimeda commented on [Mon Feb 27 2017](https://github.com/dotnet/core-eng/issues/404#issuecomment-282865903)

Scope of the work that will be done in this task is limited to -

1. Single repository. Probing and acquisition scripts will be limited to dotnet/CoreFx.
2. Single prerequisite i.e., CMake, This means scripts will probe, and acquire missing CMake.
3. Single source for CMake acquisition. Acquire CMake from OSS repository.

**Tasks**:
- [ ] Process to host a version of CMake on OSS repository is defined
•	Document a repeatable and reliable process of downloading the source of the declared CMake version, performing a security audit on the source, build the sanitized source, package and host it on OSS Tools repository.
•	Ensure the package corresponding to the declared version of CMake for each .NET Core repository is hosted in OSS Tools repository.

- [ ] Official build step to acquire declared version of CMake from OSS repository is prepared
•	In official builds, prepare a build step that will acquire the package corresponding to the declared version of the repository being built. Package should be acquired from the OSS Tools repository.

- [ ] Developer guidelines are updated
•	Update developer guidelines document to point to .toolsversions, which will contain the declared version of CMake for the repository.

---

@ravimeda commented on [Mon Mar 06 2017](https://github.com/dotnet/core-eng/issues/404#issuecomment-284507218)

@dleeapho I suggest splitting this into two User Stories as follows:

1. As a repo owner, I have a defined process to host a build tool at OSS Tools repository.
2. As a repo owner, I can follow a contract and process to declare a version of a build tool, and provision it for official and CI builds.

First one will be in Sprint 115, and the other in Sprint 116.  Please let me know if this is acceptable.

---

@ravimeda commented on [Mon Mar 06 2017](https://github.com/dotnet/core-eng/issues/404#issuecomment-284619117)

#549 tracks the work for determining the process for hosting a package at OSS Tools repository. I work on it in this sprint.

Moving this task (#404) to Sprint 116 since it is dependent on #549

**Comment by markwilkie** [comment]
@Chrisboh - I think this might be accomplished with OS Onboarding plus policy.  Thoughts?

**Comment by shawnro** [comment]
I think this was native bootstrapping, wasn't it?

**Comment by dleeapho** [comment]
This should be OS Onboarding from the infra side but originally it was conceived to encompass the contributor-dev experience. Not bootstrapping but toolset policy.

**Comment by markwilkie** [comment]
Yea to @dleeapho point, the bootstrapping stuff currently works, but we don't yet have policy in place to be consistent across the repos.  Adding this to guidance...

**Comment by Chrisboh** [comment]
The comments seem to focus around cmake, which I think we want to bootstrap, is there more to this than that?

**Comment by markwilkie** [comment]
@Chrisboh - yes, this gets to not have multiple versions of the same tool when not necessary.  I've added it to the guidance epic as we need to provide guidance (and maybe even some checks)

**Comment by markwilkie** [comment]
According to https://github.com/dotnet/arcade/blob/master/Documentation/Policy/DefaultsGuidance.md, everyone should be using the same unless there's a good reason not to.  

However, today, Arcade is not enforcing tools used by repos.  If this becomes something that needs to happen, we should discuss further as it will be a challenge and have far reaching consequences.
