### ISSUE TITLE
Release Team can ship the product with confidence

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6418]
# Release team can ship the product with confidence

The goal of this effort is to provide the release team with a reliable automated process for releasing the .NET product to our customers. Currently, we have two pipelines--the [Stage-DotNet pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=792) and an [RM pipeline](https://dev.azure.com/dnceng/internal/_release?_a=releases&view=mine&definitionId=93)--for releasing the product, plus many manual steps that must be run. These two piplines are exclusively for .NET 5.0+. While thse two pipelines-and the manual steps--can be used to release the product, they still present many challenges in terms of reliability, and in cases of complex releases--i.e. sdk only releases or releases with multiple sdks--they cannot fully release the product today without manual intervention. In this epic, we will improve the reliability of the pipelines, reduce the number of manual steps still needed to complete release activities, and define the ownership of the phases of the release.

## Business Objectives

This epic is complete when:

- [x] The release process and associated activities are reliable and maintainable, with less than 5% of jobs failing due to  infrastructure related errors
- [x] Responsibilities for release activities (running the pipeline, notification of failures, fixing validation failures, etc.) are understood, defined, and communicated to the responsible teams.
- [x] Release activities/operations ownership is confirmed by the release team as ready to be transitioned
- [x] Validation failures can be trusted, the responsible parties can be notified, and responsible parties can responded to the failures
- [x] Stage-DotNet can be used for all types of releases for .NET 5+ including full releases, sdk only releases and releases with multiple sdks

## Timeline

Deliverable | Date | Owner | Notes
----------- | ---- | ----- |-----
Sdk only releases | 4/20 | Michelle | Done
Multiple sdk releases | 5/14 | Michelle | Done
Repo tagging | 5/31 | Epsi | Done
Additional publishing activities | 7/30 | Michelle | Done
Publishing for 3.x | 5/15 | Michelle | Done
Staging environment | 8/27 | Jon | Done
Notifications | 8/23 | Michelle | Done
RACI table for Releases | 5/25 | Michelle | Done
Mariner Signing | 8/6 | Epsi | Done
Pipeline handoff to release team | 9/10 | | Done

**Comment by wtgodbe** [comment]
I'm interested in the progress of https://github.com/dotnet/arcade/issues/5482, https://github.com/dotnet/arcade/issues/6777, https://github.com/dotnet/arcade/issues/5484, and https://github.com/dotnet/arcade/issues/5483. @adiaaida please keep me in the loop on the status of these issues (CC @Pilchie)

**Comment by wtgodbe** [comment]
In addition to the above, the staging pipeline should push all shipping .nupkg's to a feed that can be used for validation (This might already work in 5.0, but as of last month wasn't working yet in 3.1).

@adiaaida do you have an update on the status of these items?

**Comment by wtgodbe** [comment]
CC @markwilkie - the relevant issues are in my 2 comments above

**Comment by adiaaida** [comment]
> In addition to the above, the staging pipeline should push all shipping .nupkg's to a feed that can be used for validation (This might already work in 5.0, but as of last month wasn't working yet in 3.1).
> 
> @adiaaida do you have an update on the status of these items?

This should be working now.
