### ISSUE TITLE
Any coherent build is shippable

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6539]
In .NET 5 and prior, we create stable builds at the end of the release cycle. This is problematic because we inevitably need to do more than one build of a repo at a specific version and flowing stable versions between repos presents significant challenges:
- Feed management
- Asset identification
- Partner build access (stable assets that are not final can pollute the nuget cache)

Because of the cost, we even avoid generating stable versions in preview builds. This can lead to confusion as the version of each runtime component varies (e.g. `5.0.0-preview.3.1234.5` and `5.0.0-preview.3.6789.0`).

**Business goals**
- We are able to safely provide pre-release builds of RTM and servicing releases to internal and public users
- We can release official preview/rc builds without build number suffixes on packages.
- Dependency flow is robust in the event of a Maestro data loss scenario

This epic is complete when
- [ ] A build can be rebranded in staging to have the desired branding.
- [ ] No isolated feeds are required to perform a .NET 6 build
- [ ] All assets in a build can be uniquely identified by their name + version.

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

**Comment by markwilkie** [comment]
@mmitche says "this is a bad idea".  To be clear, making every build be shippable is great - but this approach is not good.
