### ISSUE TITLE
Migrate to the new localization system (OneLocBuild)

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#6842]
## Motivation & Business Impact
The localization team is moving to a new system and turning of the old one on 31 March 2021. We own localization (including [xliff-tasks](https://github.com/dotnet/xliff-tasks)), so in order for our customer repos to continue localizing, we need to migrate Arcade to this new system.

## Business Objectives
- [x] Migrate to the common pipelines to the [OneLocBuild task](https://ceapex.visualstudio.com/CEINTL/_wiki/wikis/CEINTL.wiki/107/Localization-with-OneLocBuild-Task).
- [x] Ensure this works for all customer repos
- [x] Make sure this works for all supported .NET releases

## Milestones
|                         Task                         | Target Date | Date of Completion | Notes |
|:----------------------------------------------------:|:-----------:|:------------------:|:-------------:|
| Design doc on generating LocProject.json created and signed off on |  02/10/2021 |  02/10/2021 | |
| LocProject.json generated at build time (or a system is in place for helping the repos manage their LocProject.json files in a straightforward way) |  02/19/2021 |  02/19/2021  | |
| Integrated OneLocBuildTask fully in common pipeline and tested with two production repos | 03/17/2021 | 03/16/2021 | Dates adjusted due to discovery of missing feature to submit PR from Internal to Github<br/><br/>03/12/2021 - Dates adjusted again based on new format from templating team  |
| All repos with official builds pulling from AzDO migrated to OneLocBuild |  03/30/2021 | 3/30/2021 | Currently (3/19) blocked from migrating any pipelines that pull directly from GitHub by Barry<br/><br/>Update 3/25: interactive-window blocking full rollout by being broken until 3/29; winforms, Pythia, and VSUnitTesting blocked by delayed arcade promotion<br/><br/>Update 3/30/2021: Marking as complete; all repos merged or ready to merge & waiting on repo owners. |
| PRs back to GitHub implemented | 05/05/2021 | 05/05/2021 | Targeting a temporary solution for 04/29; long-term solution will be delivered by the loc team in early June<br/><br/>Update 4/30/2021: A temporary solution was used for the 16.10 release manually; a more robust solution has been retargeted for 5/05<br/><br/>Temporary solution worked for 16.10 release. Waiting on loc team's implementation for full automation in June. |
| Servicing releases with OneLocBuild documented |  05/13/2021 | 05/12/2021 | |

__________
<details>
<summary>Old objectives</summary>
1. Include 1loc into arcade yaml. example https://github.com/microsoft/powerquery-parser/blob/master/.pipelines/1loc.yml<br/>
2. Add a new feature to XLFtask to generate and keep the index file `LocPaylod.json` in sync<br/>
3. Generate a language neutral xlf (essentially just generate file MyStrings.xlf instead of MyStrings.**en**.xlf) and include it in `LocPaylod.json` 
</details>

**Comment by RussKie** [comment]
I didn't know it is being worked on centrally. I have a draft in dotnet/winforms that runs the OneLocBuild task from a cli: https://github.com/dotnet/winforms/compare/loc_update

> LocProject.json generated at build time

I'm not sure how feasible it is - I had written a script to pull all resx files we had in the repo, but then I had manually remove few files. A script to generate a file would be good, but it is quite likely that each repo owner may need to tweak the LocProject.json after that.

**Comment by JakeRadMSFT** [comment]
We need this! (We use Arcade)

**Comment by jonfortescue** [comment]
Only remaining outlier is the PRs back to GitHub which are being delivered by the loc team in June. That is being tracked by dotnet/core-eng#12670.
