### ISSUE TITLE
Move CoreFx to .NET Core 3 Engineering Ecosystem

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#687]
- [x] Public CI is using VSTS (https://dev.azure.com/dnceng/public)
- [x] Official builds in VSTS (https://dev.azure.com/dnceng/internal)
- [x] Build using shared toolset (Arcade SDK)
- [x] Dependency flow is enabled

**Comment by weshaggard** [comment]
Closed #684 as corefx is now consuming and using arcade sdk.

**Comment by chcosta** [comment]
This is done
