### ISSUE TITLE
Move Winforms to .NET Core 3 Engineering Ecosystem

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#707]
- [x] Public CI is using VSTS (https://dev.azure.com/dnceng/public)
- [x] Official builds in VSTS (https://dev.azure.com/dnceng/internal)
- [x] Build using shared toolset (Arcade SDK)
- [x] Dependency flow is enabled

**Comment by danmosemsft** [comment]
@ericstj should this go to a Winforms owner?
