### ISSUE TITLE
Move Templating to .NET Core 3 Engineering Ecosystem

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#717]
- [x] Public CI is using VSTS (https://dev.azure.com/dnceng/public)
- [x] Official builds in VSTS (https://dev.azure.com/dnceng/internal)
- [x] Build using shared toolset (Arcade SDK)
- [x] Dependency flow is enabled

**Comment by chcosta** [comment]
Tracking item for review is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/695027, that item will get reviewed and assigned a dev and we will be able to have a better conversation about the timeline

**Comment by chcosta** [comment]
This is done
