### ISSUE TITLE
Dependency flow updates without requiring a PR

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7199]
# Motivation
In order to speed up servicing release build times, we should add an option to merge dependency updates for channels that don't see breaking changes regularly without requiring running a PR build to validate the changes beforehand.

# Business Objective

[ ] Reduce the number of builds required to ship servicing releases of the product by skipping the PR build portion of the dependency update
[ ] PRs are only necessary when action is required by repo owners.

[One pager](https://github.com/dotnet/core-eng/blob/main/Documentation/Project-Docs/Dependency%20Flow/improved-dependency-flow.md)

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [ ] https://github.com/dotnet/arcade/issues/4754
- [ ] https://github.com/dotnet/arcade/issues/5133
- [ ] https://github.com/dotnet/arcade/issues/5137

**Comment by markwilkie** [comment]
@riarenas - looks like we agree that this can be closed.

**Comment by riarenas** [comment]
Yep. We determined that even for servicing branches, dependency update PRs have caught enough issues that it seems risky and low value to finish implementing this.
