### ISSUE TITLE
Build Arcade with Arcade

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#72]
Arcade building Arcade is one important aspect (requirement) for using Arcade as a repo "template".  Arcade needs to demonstrate how to build using itself so that it can be used as a starting point (or adoption goal) of other repos.  Basically, anyone should be able to simply clone, then build Arcade.

The first step was to get Arcade building and publishing packages in the open.  (#45)  Now, it is important to take the next step of building Arcade using itself.  This epic is considered complete when:
- [x] Final versioning plan is complete and implemented
- [x] Signing approach and implementation complete
- [x] Bootstrapping the CLI plan is complete and implemented  (native tools are next)
- [x] build.cmd/sh is implemented 
- [x] Cloning Arcade on a clean machine, then typing "build" works to build Arcade.
