### ISSUE TITLE
Onboard optimization repo to use arcade publishing

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7243]
- [x] Help create channels and subscriptions for optimization repo
- [x] Onboard dependency flow 
- [x] Onboard optimization repo to arcade publishing 
- [ ] Help optimization repo to arcadify

**Comment by epananth** [comment]
this issue does not have any epic.

**Comment by markwilkie** [comment]
I'm fine w/ you just turning this issue into an epic Epsi.  Just be sure and add the checkboxes please, and if you're unclear on those, we can chat.

**Comment by epananth** [comment]
okay will do.

**Comment by epananth** [comment]
Optimization repo is using arcade to publish, closing this epic :)
