### ISSUE TITLE
Move MSBuild to .NET Core 3 Engineering Ecosystem

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#727]
- [x] Public CI is using VSTS (https://dev.azure.com/dnceng/public)
- [ ] Official builds in VSTS (https://dev.azure.com/dnceng/internal)
- [x] Build using shared toolset (Arcade SDK)
- [x] Dependency flow is enabled
