### ISSUE TITLE
Backporting publishing v3 to Arcade 3.x 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7431]
The 3.x version version of arcade should move to using the v3 publishing. This will allow the addition of new channels without rolling out new arcade versions, as well as unifying publishing. When complete:

Backporting work:
- [ ] Remove legacy publishing code from arcade main
- [ ] Arcade 3.x will produce and use v3 publishing by default.
- [ ]  Remove legacy publishing code from arcade release/3.x
- [ ]  Remove legacy publishing code from arcade release/5.x
- [ ] All arcade 3.x repos will have moved to v3 publishing. (Repos and Branches that take arcade updates from 3.x will move to V3 publishing)

Improvements/Additions:
- [ ] Improve Symbol publishing performance. Eg: Should stop publishing Symbols to nuget feed instead, forcing all the symbol packages to have non-stable versions. 
- [ ] Add support for publishing vssdk/vs-impl artifacts
- [ ] Update tests and documentation 

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [ ] https://github.com/dotnet/arcade/issues/5304
- [ ] https://github.com/dotnet/arcade/issues/5308
- [ ] https://github.com/dotnet/arcade/issues/5390
- [x] https://github.com/dotnet/core-eng/issues/10217
- [x] https://github.com/dotnet/core-eng/issues/10324
- [ ] https://github.com/dotnet/arcade/issues/6089
- [ ] https://github.com/dotnet/arcade/issues/6118
- [ ] https://github.com/dotnet/arcade/issues/6574
- [ ] https://github.com/dotnet/arcade/issues/6626
- [ ] https://github.com/dotnet/arcade/issues/6802
- [ ] https://github.com/dotnet/arcade-services/issues/2451
- [ ] https://github.com/dotnet/arcade/issues/6881
- [ ] https://github.com/dotnet/arcade/issues/6909
- [ ] https://github.com/dotnet/arcade/issues/6931
- [x] https://github.com/dotnet/arcade/issues/6932
- [x] https://github.com/dotnet/arcade/issues/6933
- [x] https://github.com/dotnet/arcade/issues/6945
- [x] https://github.com/dotnet/arcade/issues/6946
- [x] https://github.com/dotnet/arcade/issues/7011
- [ ] https://github.com/dotnet/arcade/issues/7019
- [ ] https://github.com/dotnet/arcade/issues/7349

**Comment by markwilkie** [comment]
Update from @mmitche.  This is still useful from a security standpoint and @epananth might be writing a one-pager?

**Comment by mmitche** [comment]
Not gonna happen.

**Comment by adiaaida** [comment]
@mmitche did you mean to reopen this?

**Comment by mmitche** [comment]
It has a bunch of issues that need triaging so I reopened it to not lose track of them.

**Comment by epananth** [comment]
We are likely not making any changes to 3.1 

So closing this epic 

cc: @mmitche
