### ISSUE TITLE
Provide shared localization capability 

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#760]
This epic is considered completed when:

- [ ] Localization tools/services are sharable across teams (likely as part of arcade)
- [ ] There's clear guidance on how to localize
- [ ] At least 2 repos have implemented

**Comment by markwilkie** [comment]
From: Livar Cunha <licavalc@microsoft.com>
Date: Thursday, September 13, 2018 at 10:30 AM
To: Mark Wilkie <mawilkie@microsoft.com>, Shawn Rothlisberger <shawnr@microsoft.com>, Peter Marcu <Peter.Marcu@microsoft.com>
Subject: Re: Localization
 
Hi, yes, xliff-tasks has been working extremely well for us and is now maintained by Tom Mescher, who is the current loc champion on the tooling side.
 
It is used by us, Roslyn, I believe MSBuild, fsharp and a few other repos. It might already be part of arcade, as I believe it was part of repotoolset.

**Comment by jcagme** [comment]
> Localization tools/services are sharable across teams (likely as part of arcade)

As in this been part of the SDK?

**Comment by markwilkie** [comment]
Maybe - we'll discuss.  I want to reach out to Tom Mescher first as this may be another symbols publishing situation where the code lives elsewhere.

**Comment by tmat** [comment]
Localization is definitely part of Arcade SDK. Already used by all repos using RepoToolset.

**Comment by markwilkie** [comment]
Closing as complete
