### ISSUE TITLE
Define and Implement Repo API

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#85]
As part of the prodcon effort, a repo API needs to be defined and implemented.  This epic is considered complete when:
- [ ] Repo API is defined
- [ ] Repo API is implemented in Arcade
- [ ] Repo API is implementable for the rest of the repos in the stack

**Comment by markwilkie** [comment]
This is not really emerging as a "thing".  Rather, the work is currently being tracked under the prodcon v2 epic.  If needed in the future, we'll create a new epic.
