### ISSUE TITLE
Prepare Dev WF Grafana alerts for end of epic

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8751]
The alerts for the Dev WF services currently contain placeholder information. Before we close up the epic, we should ensure that each of these alerts contains: 

- [x] Actionable information for how to investigate/troubleshoot the alert
- [x] Links to more detail (to a wiki page, or whatever is agreed upon by the team) 

The goal should be that anyone who is tasked to investigate this in FR should be able to understand what is needed to be done with the alert without needing to seek out tribal knowledge from a Dev WF dev. 

### Release Note Description
No release notes

**Comment by missymessa** [comment]
- [ ] Ensure that the alert and Grafana panel names as consistent: https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1657742563111?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1657706755706&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1657742563111

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/29280
