### ISSUE TITLE
Build Analysis UX changes per UX designer feedback

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9066]
Dan's gist for reference: https://gist.github.com/danmoseley/f56e2cdb7e2e9579b7b78e69c3af2a95

The UX designers recognized that we have a "signal to noise" problem with the information we're attempting to convey on the Build Analysis page. They recommended two design patterns to help: "Progressive Disclosure" and "Expand Collapse". 

- [x] The designers liked how Dan's gist included larger headers, and suggested we do the same for each of the build failures (looks like we already do this for test failures, so we should make it consistent). (https://github.com/dotnet/arcade/issues/9468)
- They liked the way we used emojis, but suggested two updates: 
    - [x] On the "All good" page, use a green checkmark if possible. This signals to the user that everything is good, without the black checkmark getting lost on the page. (https://github.com/dotnet/core-eng/issues/13363)
    - [x] Use a clock face emoji instead of the hourglass on the "waiting" page, because the hourglass is anachronistic. (https://github.com/dotnet/arcade/issues/9468)

If possible (because this is GitHub's flavor of markdown we're using here): 
- [ ] Collapse subsequent headers (e.g. Build Failures, Test Failures) to reduce the amount of initial noise. Allow users to expand those headers when they're ready to read that information. **note**: this is possible, but we were concerned about number of clicks. 
- [ ] Alternatively, wrapping the exception messages (like how Dan did in his gist) helps the eyes and brain to perceive that information as optional and can glance past it. **note**: can't do this without GitHub fixing wordwrapping on their end

**Comment by ChadNedzlek** [comment]
Dan gist did the opposite of wrapping the message, and will get... interesting... with longer build errors, since putting them in code blocks make them stop wrapping, so often the important information will require a horizontal scroll bar, which if I recall correctly, is a bit usability no-no (we already have sentiment feedback about existing non-wrapped text)

**Comment by missymessa** [comment]
> Dan gist did the opposite of wrapping the message, and will get... interesting... with longer build errors, since putting them in code blocks make them stop wrapping, so often the important information will require a horizontal scroll bar, which if I recall correctly, is a bit usability no-no (we already have sentiment feedback about existing non-wrapped text)

What was the sentiment feedback regarding the non-wrapped text?

**Comment by ChadNedzlek** [comment]
This one: the sentiment is https://github.com/dotnet/arcade/issues/9029.  The sentiment is literally: "Many of the errors too long and not word-wrapped, which means I would need a horizontal scrollbar which is also missing.".

**Comment by missymessa** [comment]
My take is we see if it's even possible to make the code block work, considering the limitations we have with GitHub markdown. If we can't do it at all, it's a moot point. Alternatively, we can see if collapsing the stack traces works instead, since that would: 1) allow that information to be hidden until the user wants to view it and 2) would not be word-wrapped. 

Also, when we do the subsequent user study, we can make sure to get customer feedback about however we handled these sections of data.

**Comment by ChadNedzlek** [comment]
We do need to be careful not to go _too_ collapse happy, since that just adds clicks to users flow (if they ALWAYS have to click to get at the exception message, that's going to get really annoying really fast). What's the benefit of adding the clicks?

**Comment by ChadNedzlek** [comment]
The sad part is, because of how limited we are in size, there isn't actually _that_ much we can collapse away. I wish we could add tons of cool details, hidden behind a collapsy bit... but we are having trouble even including the critical stuff. :-)

**Comment by missymessa** [comment]
> We do need to be careful not to go _too_ collapse happy, since that just adds clicks to users flow (if they ALWAYS have to click to get at the exception message, that's going to get really annoying really fast). What's the benefit of adding the clicks?

My thought was that we'd collapse the longer stack traces, what were you thinking?

**Comment by ChadNedzlek** [comment]
If they are too long, perhaps we could compact them.  Usually the top and bottom of the stack traces are the interesting bits (this would be one of the things we can try when we get the "you failed because it's too long" message).  Usually only the top few and bottom few stack frames are actually interesting.  But I could see maybe having the first line of the exception message be a "summary", and then having the full stack inside.  Though we'd have to make sure the first line wasn't useless (if it was just something like "at XUnit.Equals" that's not useful without expanding)

**Comment by missymessa** [comment]
If we truncate/compact stack traces, how is that different/better than requiring a user to scroll to see the full context of the stack trace? At that point, we're removing information that they may feel is important.

**Comment by missymessa** [comment]
Either way, this is something that should be paid attention to in a user study and we'll adjust the UX accordingly. If the majority of users prefer one way over another, we should go with the greater preferred style.

**Comment by alexperovich** [comment]
You could start compacting the stack traces by removing all the "async goo" that ends up in stack traces. The "TaskAwaiter.ThrowForNonSuccess" type frames.

**Comment by missymessa** [comment]
For reference, this was the screenshot of a failing PR (had all the elements for a failed PR I was hoping to capture) I showed the UX Designers: 

![image](https://user-images.githubusercontent.com/47990216/163628695-19939f70-3929-4e83-bb90-045adce1f3b7.png)
![image](https://user-images.githubusercontent.com/47990216/163628718-8a1725f2-8366-4785-bdb8-91418620b58e.png)

**Comment by ChadNedzlek** [comment]
Ouch, yeah, that's a really crappy log message.  The name of the leg that failed could stand to be a H3 or H4, couldn't it (like the test names).  Then we don't need a bulleted list under it, saving us some horizontal space.  Though then the [Report Issue] links need to go on the line below it (which is probably a good idea anway, so they are more predicably located... UI on the right of lines of text is rough, especially when things might wrap)

**Comment by ChadNedzlek** [comment]
Though to be fair, _most_ error messages don't look like that.  Most of them are tiny little one-liners. It's only when our Build tasks crash out without handling it that we tend to get the ginormous callstack type errors.  Maybe we need some sort of detection/UI different to deal with those?

**Comment by AlitzelMendez** [comment]
After reading the feedback and all the comments I put together the following mockups.
Please share your feedback.
I added a link in where you can see this a check run with these mockups so you can see the size of the title and how everything is rendered. 


### [Mockup A](https://github.com/AlitzelMendez/build-result-analysis-test/pull/41/checks?check_run_id=6560113029)
<img width="1534" alt="PropuestaA_01" src="https://user-images.githubusercontent.com/6895254/169874316-5d63451f-e58f-4dd0-897f-76d22aba47b7.png">

### [Mockup B](https://github.com/AlitzelMendez/build-result-analysis-test/pull/41/checks?check_run_id=6560123206)
Before expanding 
<img width="1535" alt="PropuestaB_01" src="https://user-images.githubusercontent.com/6895254/169874385-c4f81a19-a76a-453d-a5f3-fffaa0fcb4c6.png">

After expanding
<img width="1523" alt="PropuestaB_02" src="https://user-images.githubusercontent.com/6895254/169874407-e3c278a0-1e11-48c7-a27c-5e42cc605c6d.png">

**Comment by ChadNedzlek** [comment]
Are there updates to the test part too?  I think I prefer Mockup B, myself.  The gray chunk in the middle really drew my eye, and I don't think it was supposed to.  I kept trying to figure out why it was gray and nothing else was.  I don't... _think_ there is anything different about that particular error message other than it's a bit long? But the UI seems to be trying to tell me _something_ is different, since it's rendered different, but it doesn't say what that difference is. :-)

**Comment by AlitzelMendez** [comment]
I split this issue into this: https://github.com/dotnet/arcade/issues/9468 to address larger headers, clock face emoji and Make build failures and test failures consistent.

There are still things missing like how we are going to handle long build errors.

**Comment by danmoseley** [comment]
I do not believe it makes sense to present arbitrary test output, stack traces etc in a proportional font. It's harder to read (we all use fixed width for our work), and it doesn't line up columns which can make it harder to pick out details, and breaks some ASCII-art type arrows that some tools emit. I also don't think it should wrap, for a similar reason. So "A" is better for those reasons.

The lines around "test run aborted" etc are quite widely spaced. If we can reduce blank vertical space, it's less likely I hvae to scroll.

**Comment by ChadNedzlek** [comment]
The only tricky bit can be the amount of horizontal scrolling that might get introduced, but it's mostly a trade-off.  I think for test stuff, which is almost always using alignment tricks (the arrows in expected/actual, or the " at PLACE" in the callstacks) probably make me lean more for it making sense in test output/callstacks.

It's the build errors/logs where the tradeoff is a little more... nebulous to me. Error messages can often be very long, often with important information far to the right (like which csproj file the erorr was in), and they use alignment tricks of proportional fonts a lot more rarely.
