### ISSUE TITLE
.NET 8: Virtual Mono Repo (VMR) Lite

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#9359]
This epic is about investigation of how we can effectively build up the Virtual Mono Repo, keep it in sync with the individual repositories, implementing a proof of concept and then productionizing it into a "lite" version of the full VMR.

📄 [General Mechanics document](https://microsoft.sharepoint.com/:w:/t/Salmon.NET/Eb0zADSifUBKsJubPa4ZpVYBwunSBi8F62uu4BkQc8ZkNg?e=UfIcQy) - describes the operation of the full VMR.

The ultimate goal of this epic is for us to have an (internal) VMR-lite which could serve the same purpose as the source-build tarball does today. We should eventually be able to discard the tarball and use the VMR only as the source for the source-build and as a place where we can work on the source-build.

What we are thinking is that we utilize the fact that source build already mirrors how a VMR build works. Right now, the SHAs that source-build uses are determined by normal Maestro dependency flow, based on specific entries in dotnet/installer's `Version.Details.xml` files. We can mirror this process into a git world and assemble the VMR similarly.

# VMR-lite requirements
VMR-lite is a first milestone on the way to the full VMR with some limited capabilities compared to the full VMR described in the [General Mechanics document](https://microsoft.sharepoint.com/:w:/t/Salmon.NET/Eb0zADSifUBKsJubPa4ZpVYBwunSBi8F62uu4BkQc8ZkNg?e=UfIcQy):
- It is _read-only_ meaning no changes done to the VMR will flow back to the individual repos automatically yet.
- It can be initialized from ground up using any `dotnet/installer` commit by using the SHAs from its `Version.Details.xml`.
- It can update its contents (mirrored individual repos) from one SHA to another by diffing the individual repos and applying this change.
- We can build the RedHat/Canonical product from it (i.e. it is interchangeable with the tarball) and it does not contain binaries / files with invalid licenses (i.e. ready for a handover to Canonical).
- We are able to validate its readiness as part of the `dotnet/installer` PR build.

# Business objectives
- [x] We have a clear idea of how the VMR may work (on the input flow and build side)
- [x] We know what the success and failure rates of the VMR flow and build are and their types, so we can triage them as ones we should expect in a true Unified Build implementation, and which ones are specific to the POC
- [x] VMR for .NET 8 is created and its sources are automatically synchronized
- [x] VMR is used to release / service source-build for .NET 8 preview 1

# Technical objectives
- [x] #10257
- [x] #10268
- [x] #10258
- [x] #10677
- [x] #10961
- [x] #11886
- [x] https://github.com/dotnet/source-build/issues/3194

**Comment by premun** [comment]
Status update:
- Created the VMR in AzDO ([dotnet-vmr](https://dev.azure.com/dnceng/internal/_git/dotnet-vmr))
- Created tooling to synchronize the VMR ([dotnet-vmr-tools](https://dev.azure.com/dnceng/internal/_git/dotnet-vmr-tools))
- Created a pipeline that synchronizes the VMR every 3 hours ([dotnet-vmr-synchronization](https://dev.azure.com/dnceng/internal/_build?definitionId=1156&_a=summary))

**Comment by mmitche** [comment]
@premun Updated the title to more accurately reflect the work

**Comment by premun** [comment]
Closing this epic as Preview 1 was shipped from the VMR and that was the ultimate goal of this epic
