### ISSUE TITLE
SDL Pass for DncEng-owned areas, Spring 2022

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#9442]
## Goals

- [ ] Spring SDL 2022 Assement completed for all the following areas
- [ ] Rollup summary of outcomes is written up and shared with dotnetes team 

## Milestones
| Assessment | Owner | Estimated Date of Completion | Status | 
| --- | --- | --- | --- |
| Helix | @MattGal | 2022-07-01 | Complete | 
| Arcade | @MattGal | 2022-07-01 | Complete | 
| Arcade Services - Maestro | @garath | 2022-08-15 | Complete (awaiting threat model review) | 
| Arcade Services - Grafana | @garath | 2022-07-01 | Completed | 
| Arcade Services - DotNet Status Web | @jonfortescue | 2022-07-15 | Complete | 
| Arcade Services - Rollout Scorer | @jonfortescue | 2022-07-15 | Complete | 

### Helix
- [x] https://github.com/dotnet/arcade/issues/9443

### Arcade
- [x] https://github.com/dotnet/arcade/issues/9444

### Arcade Services - Maestro
- [ ] https://github.com/dotnet/arcade/issues/9445

### Arcade Services - Grafana
- [x] https://github.com/dotnet/arcade/issues/9446

### Arcade Services - DotNet Status Web
- [ ] https://github.com/dotnet/arcade/issues/9447

### Arcade Services - Rollout Scorer
- [x] https://github.com/dotnet/arcade/issues/9448

**Comment by jonfortescue** [comment]
Completed as of 15 July closing.
