### ISSUE TITLE
Test logs search API

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9522]
# Goal

Developers for .NET applications need a way to easily find where a specific error has occurred in their failed tests. We want to build an API that given a repository and error message, will return the occurrences of the error in the repository's failed test logs.

## Business Objectives
- [x] P0: Developers can make a call to an API to search for all available Helix test logs that contain a specific error message to help with error investigation
- [x] P1: Developers can refer to written documentation to understand how to make calls to the API.
- [ ] P2: Developers can interact with the API through a CLI/UI

## Timeline
Week    | Milestone | Status
------  | ------ | ------------------------------------------------------------------------------------------------ |
 1      | Onboarding + Introduction to project, Dev environment set-up | Complete
 2      | Learn Helix basics, write design document | Complete
 3      | Get design document reviews and start implementing POC   | Complete
 4      | Finish implementing POC | Complete
 5      | POC testing and findings documentation + start implementing API | Complete
 6      | Continue API implementation  | Complete
 7      | Finish API implementation  + integrate possible additional features from design doc | Complete
 8      | API testing + documentation  | In progress
 9      | API testing + documentation | In progress
 10      | Prepare for customer presentation | Not started
 11      | Customer presentation | Not started
 12      | Final week :)
 
 
 
## One-pager

The one-pager PR can be found [here](https://github.com/dotnet/arcade/pull/9382)

**Comment by ulisesh** [comment]
We didn't get to build a CLI during Amanda's internship, the DevWF team will continue to work on this

cc @missymessa @AlitzelMendez
