### ISSUE TITLE
SourceBuild Repo Level Prebuilts Detection

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade#9672]
**This is a draft, will be filled in properly yet**

# Motivation

Currently, the prebuilts detection is done not on the repo level, but at time when the products is being assembled together. The goal of this epic is to enable prebuilts detection on the repo level.

# Milestones

- [ ] Replace the current GenAPI tooling to use the new Roslyn features to generate SBRP sources
- [ ] Enable repo-level prebuilts detection in all product repos
- [ ] Improve customer experience when generating the SBRPs
